### PR TITLE
support android 4.4

### PR DESCRIPTION
**Pull request by lujnan**
Support for android 4.4 system.
1. The android 4.4 lacks of 'pthread_condattr_setclock', 'initstate'、'stpcpy', 'ifaddrs', such functions. 2. The 'pthread_cond_timedwait' function only support 'CLOCK_REALTIME' on Android 4.4.
3. Add android port  of libconfig, libpopt. 
4. Not support libsoxr.

### CODE REVIEW

**Comment by mikebrady** [comment]
Hi there. This is good work, but unfortunately I have some problems with it.

It seems that there are three kinds of things going on:

1. Android seems to lack support for some variations of `pthread` functions. I think it is fully acceptable that an Android compiler flag is used to select a variant that is available in Android. So, I'm fine with that.

2. Android does not seem to implement some common Linux functions that Shairport Sync uses. I think that it is more appropriate these should be implemented separately as a kind of Android compatibility library – in fact, this may already have been done. If not, I suggest you put it out as a separate repository. But I think it is inappropriate that these should be part of Shairport Sync.

3. Android does not have some standard libraries. It does not make sense that those libraries should be part of the Shairport Sync repository; they should be made available as separate repositories. As I said above, they may already be available. If not, it would make sense to host them yourself on GitHub. It would be inappropriate to include these in Shairport Sync.

Maybe some other users who are more familiar with Android would be able to comment.

**Comment by lujnan** [comment]
Ok, I will try to port some Libs to android, there are libsoxr, avahi, alsa, need port, other libs now are available, and, I will remove the libconfig, libpopt from master branch, and move to other repo. could you give me some advice about some c functions lacked on android, where put them.  The android 5.0 is more power support for the pthread lib. And I need to port arm64 arch build config.

**Comment by mikebrady** [comment]
TBH, I don't know. If I was doing this, I suppose I'd start by trying to build a small library, e.g. `libandroidssncsupport`, or something like that with the functions in it.

Thanks again for this – I think it will be useful to a lot of people.

**Comment by mikebrady** [comment]
Hello again. I realise that you have put a lot of work into this, but unfortunately, it still has lots of problems, many of which I referred to before. I am therefore respectfully going to decline the pull request. Here, again, are some reasons:

1. You seem to be including source code for other libraries, e.g. `libconfig`, `libpopt`, in the pull request. It is completely inappropriate for these to be included in the Shairport Sync repository.
2. You are including source code for many functions that are absent from Android. As I suggested before, these could perhaps be made into a small compatibility library that should be a separate repository. They should be written so that they are made available to Shairport Sync – or any other applications – in the standard manner. They are inappropriate of inclusion in the Shairport Sync repository. In addition, Shairport Sync should not have to be modified to look for them in different places just because it's being built for Android. 
3. You are including the file `config.h` which is automatically generated.

**Pull request closed without merging**
