### PR TITLE
Initial support for libsoundio

### PR DESCRIPTION
**Pull request by shtirlic**
Support for C library for cross-platform real-time audio input and output
http://libsound.io/
https://github.com/andrewrk/libsoundio

Everything works, please try, need suggestion about settings for software latency.

### CODE REVIEW

**Comment by mikebrady** [comment]
Hi Serg. This looks exciting. However, I wonder if it wouldn't be better targeted to the `development` branch. What do you think? It'll have to go there anyway to have a future. Would there be a lot of work in it?

**Comment by shtirlic** [comment]
Hi Mike, changed base branch and updated some code, I see that there is a new `format`  in play function, should it be mapped to the target lib formats or we are using default short 2bytes ?

**Comment by mikebrady** [comment]
Many thanks for this Serg.

I'm not sure what you are referring to.

Do you mean that there is a `format` parameter in the `init()` function? If so, that should use the enumeration defines in `common.h`. These are different, unfortunately, to the ALSA enumeration values, so they are translated into ALSA enumerations in `audio_alsa.c`. Obviously, you don't have to use ALSA stuff in your `libsoundio` stuff.

The format and the rate default to 16-bit interleaved stereo at 44,100 frames per second anyway, so you may not have to worry.

Sorry if this is not relevant to your question...

**Comment by mikebrady** [comment]
Hi Serg. I'm merging the pull request, even though I don't know whether you message of December 3 means it doesn't work. Let us travel hopefully :)

**Comment by shtirlic** [comment]
Hi Mike, I mixed up the method name it was `start` 's new format param, but it's ok since I use 16-bit interleaved stereo at 44,100 by default, I will add correct mappings will encounter issues with custom formats.

**Comment by mikebrady** [comment]
Great, thanks.

**Pull request merged**
