### PR TITLE
Various minor fixes

### PR DESCRIPTION
**Pull request by acli**
Various minor fixes – same changes as in the previous patch but retargeted to the development branch

### CODE REVIEW

**Comment by mikebrady** [comment]
Thanks. I see you're still adding to it...

**Comment by acli** [comment]
My Pi just died; it looks like the SD card failed again. I don’t think I’ll be able to work on this any further in the next few days.

By the way, I never succeeded in getting any audio from my Pi. (It was a headless install with pulseaudio so the comments in PulseAudioAndPipeWire also have some issues.) Should I open an issue just for the record? When I get a new SD card I don’t think I’m going to image the same OS on it so I might not be able to reproduce the problem.

**Comment by mikebrady** [comment]
Thanks. I think it doesn't make a lot of sense to open an issue for the record unless we can test when/whether it's been fixed. If it comes up again, of course, flag a new issue.

**Comment by mikebrady** [comment]
Many thanks for this.

**Pull request merged**
