### PR TITLE
Add another example on Bluetooth speaker setup

### LINKED ISSUE #559: Bluetooth audio stuttering
Hello,

I'm using your great software with my rpi3 (jessie) and it worked great with an iphone and airplay but if I use my android phone and bluetooth I get a very stuttering sound.
I already tried it with the iphone and bluetooth and got the same bad sound quality.
Is this a known problem?
Is there anything I can do to get a smooth audio output?

Thanks

### PR DESCRIPTION
**Pull request by SkyZH**
Hello,
Recently I'm trying setting up Airplay on one of my bluetooth speakers. I've met with many difficulties such as stuttering sound. Finally I succeeded in delivering sound (AAC / aptX) to my speakers with `bluealsa` and enabling volume control on my Raspberry Pi, and I'd like to share my configuration with other users, which may fix (possibly) #559 and #200 . Is it possible to add this example in README.md? Thank you for reading my PR.

### CODE REVIEW

**Comment by mikebrady** [comment]
Thanks for this pull request. I wonder whether the topic of using Bluetooth speaker should be the subject of a separate thread, maybe a kind of a how-to, rather than just part of README.md. I guess I'm thinking of what one has to do to get Bluetooth audio working in the first place, which AFAIK isn't a trivial matter. What do you think?

**Comment by SkyZH** [comment]
@mikebrady Yep, I also think that connecting a Bluetooth speaker requires many setup steps, including setting up `bluealsa`, `bluez`, adding them to `systemd`, writing a script to connect bluetooth speakers when system starts, and finally, writing configuration file in `shairport-sync`. So with this example, I'd like to guide people on how to enable volume control on `bluealsa` and avoid stuttering. Maybe we can write `Enable Volume Control on Bluetooth` and `Avoid Bluetooth Stuttering` as tips, instead of an example, in `Configuring Shairport Sync` section?

**Comment by mikebrady** [comment]
Exactly. What I was thinking of was a page called something like “BLUETOOTH.md” with a guide as you have outlined above in it. Would you like to write a draft version that we could put up?

**Comment by mikebrady** [comment]
Thanks Rachel. I am going to decline this pull request, but I'd be happy to open a “BLUETOOTH.md” page instead.

**Comment by sealustsailing** [comment]
Is there a guide available? I tried following @zllovesuki 's guide however I cannot seem to get it working

**Comment by SkyZH** [comment]
@sealustsailing any log available?

**Comment by sealustsailing** [comment]
Sorry @SkyZH , I am a bit of a noob with Linux. Where would I find the log for Shairport? It is working as expected in the sense that it is outputting to 3.5mm. I did have A2DP working with ALSA but removed when following @zllovesuki 's instructions. 

Looking through the steps, the main part that seems to go wrong is in PulseAudio. I was unable to get Shairport to see it as an output_backend.

**Comment by R0dri** [comment]
Hey, this seems to be the most updated instruction set. I couldn't find the BLUETOOTH.md page... seems that this idea has been forgotten.

Should this issue be reopened? I spent the last couple of hours trying to find a guide that works installing all sort of libraries. it would really be helpful.

**Comment by skyzh** [comment]
@R0dri In this pull request, I just mentioned some additional settings that should be done after setting up bluealsa. If you find that 1. volume control not available 2. stuttering 3. audio latency, you may refer to changed file in this PR.

**Comment by R0dri** [comment]
hmm, I was not referring so much as your original conflict as to the lack of any bluetooth setup guide. I was pointing out this great idea:

> Exactly. What I was thinking of was a page called something like “BLUETOOTH.md” with a guide as you have outlined above in it. Would you like to write a draft version that we could put up?

I am thinking of adding a manual of a setup with bluetooth. Personally i struggled a while to find out I had to set up bluealsa in the first place. It is not a hard setup, but if you are as lost as I was you find yourself wasting a lot of time figuring things out. As I said, this comment could be transformed in a "BLUETOOTH.md" file guide.

**Pull request closed without merging**
