### PR TITLE
Development

### PR DESCRIPTION
**Pull request by nettings**
Hi @mikebrady, I guess the code is now in a state where you can look at it without wasting your time. I have run the code for more than 24 hours in total without any issues. I did not profile the original code, but I believe the CPU usage is significantly lower now. I did see another spurious segfault on shutdown again despite putting that client_mutex back in. I guess there is some racey stuff going on, maybe we need to resurrect the global client_is_open flag if the problem turns out to be more than cosmetic.
The ALSA mixer integration will have to wait a week, I have jobs coming up...

### CODE REVIEW

**Comment by mikebrady** [comment]
Many thanks for this. I hope to get a look at it on Tuesday -- two days from now.

**Comment by mikebrady** [comment]
Just *looking* at the changes, it seems  you put a lot of work into it! I'm looking forward to trying it out.

**Comment by mikebrady** [comment]
Many thanks!

**Comment by nettings** [comment]
Awesome, thanks! In case any issues pop up and I miss a message, just tag me and I'll try to take care of it.

**Pull request merged**
