### PR TITLE
Development

### PR DESCRIPTION
**Pull request by p3ck**
Update spec file to latest changes.

### CODE REVIEW

**Comment by p3ck** [comment]
Hi Mike,

Do you have a way of updating the version in the spec file automatically?

Version:        #PACKAGE_VERSION#??

**Comment by mikebrady** [comment]
Hi Bill. Thanks for this. I'll have a look at that PACKAGE_VERSION idea.

**Comment by mikebrady** [comment]
Bill, I was thinking about writing a line or two about how / when to use this to put in README.md. For example:

*To build Shairport Sync as an RPM package for Fedora (thanks @p3ck!), perform the command:*
```
rpmbuild -ba shairport-sync.spec
```

I've no idea if that's right – would you be kind enough to check / edit as necessary?

**Comment by p3ck** [comment]
Hi Mike,

I was away this weekend so I didn't see this until now.  If we do things
correctly you could tell your users to just do the following:

From the releases tab on github download the tarball or use wget
% wget -O shairport-sync.2.3.12.tar.gz
https://github.com/mikebrady/shairport-sync/archive/2.3.12.tar.gz
% rpmbuild -ta shairport-sync-2.3.12.tar.gz

the -ta says build all from this tarball.

**Comment by mikebrady** [comment]
Thanks. I just put up a version on the README.md page.

**Comment by p3ck** [comment]
Hi MIke,

Looks like the 2.3.12 tag doesn't have the latest changes to the spec file
so it doesn't work right now.  It will work when you make a 2.3.13 release
(and update the version in the spec file to match).

Sorry about that.

**Comment by mikebrady** [comment]
Thanks. I am an idiot™. I'll fix it.

**Comment by mikebrady** [comment]
Hi Bill. I updated it, having finally installed Fedora on a VM. There was a bit more to installing Shairport Sync on a stock machine than I thought, and my update reflects my experience. Is there anything I could streamline? Thanks for your help.

**Comment by p3ck** [comment]
Hi Mike,

This worked for me.  See the attached log.

Thanks!

On Wed, Aug 26, 2015 at 5:19 PM, Mike Brady <notifications@github.com>
wrote:

> Hi Bill. I updated it, having finally installed Fedora on a VM. There was
> a bit more to installing Shairport Sync on a stock machine than I thought,
> and my update reflects my experience. Is there anything I could streamline?
> Thanks for your help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mikebrady/shairport-sync/pull/114#issuecomment-135173312>
> .
>



-- 

Bill Peck
http://www.pecknet.com

**Comment by p3ck** [comment]
I guess attachments don't work here.. :-)

[bpeck@localhost ~]$ wget -O shairport-sync-2.3.13.1.tar.gz https://github.com/mikebrady/shairport-sync/archive/2.3.
13.1.tar.gz
--2015-08-27 08:28:19--  https://github.com/mikebrady/shairport-sync/archive/2.3.13.1.tar.gz
Resolving github.com (github.com)... 192.30.252.130
Connecting to github.com (github.com)|192.30.252.130|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/mikebrady/shairport-sync/tar.gz/2.3.13.1 [following]
--2015-08-27 08:28:19--  https://codeload.github.com/mikebrady/shairport-sync/tar.gz/2.3.13.1
Resolving codeload.github.com (codeload.github.com)... 192.30.252.144
Connecting to codeload.github.com (codeload.github.com)|192.30.252.144|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘shairport-sync-2.3.13.1.tar.gz’

shairport-sync-2.3.13.1.tar.     [ <=>                                             ] 214.27K  --.-KB/s   in 0.1s   

2015-08-27 08:28:20 (1.55 MB/s) - ‘shairport-sync-2.3.13.1.tar.gz’ saved [219411]

[bpeck@localhost ~]$ rpmbuild -ta shairport-sync-2.3.13.1.tar.gz 
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.namOag
+ umask 022
+ cd /home/bpeck/rpmbuild/BUILD
+ cd /home/bpeck/rpmbuild/BUILD
+ rm -rf shairport-sync-2.3.13.1
+ /usr/bin/gzip -dc /home/bpeck/shairport-sync-2.3.13.1.tar.gz
+ /usr/bin/tar -xf -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd shairport-sync-2.3.13.1
.
.
.
Processing files: shairport-sync-debuginfo-2.3.13.1-1.fc21.x86_64
Checking for unpackaged file(s): /usr/lib/rpm/check-files /home/bpeck/rpmbuild/BUILDROOT/shairport-sync-2.3.13.1-1.fc21.x86_64
Wrote: /home/bpeck/rpmbuild/SRPMS/shairport-sync-2.3.13.1-1.fc21.src.rpm
Wrote: /home/bpeck/rpmbuild/RPMS/x86_64/shairport-sync-2.3.13.1-1.fc21.x86_64.rpm
Wrote: /home/bpeck/rpmbuild/RPMS/x86_64/shairport-sync-debuginfo-2.3.13.1-1.fc21.x86_64.rpm
Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.ViEt1O
+ umask 022
+ cd /home/bpeck/rpmbuild/BUILD
+ cd shairport-sync-2.3.13.1
+ /usr/bin/rm -rf /home/bpeck/rpmbuild/BUILDROOT/shairport-sync-2.3.13.1-1.fc21.x86_64
+ exit 0

**Comment by mikebrady** [comment]
Thanks. That's kind-of what I got alright. It doesn't seem possible to do an automatic installation from that though, does it?

**Pull request merged**
