### PR TITLE
mbedtls: add support to mbedtls3

### PR DESCRIPTION
**Pull request by orangepizza**
It doesn't look like anything calls `havege.h`.
Signed-off-by: Seo Suchan <tjtncks@gmail.com>

### CODE REVIEW

**Comment by mikebrady** [comment]
Many thanks for this. If you could change that target of the PR the `development` branch rather than the `master` branch, it would be much easier to incorporate in the update cycle.

**Comment by mikebrady** [comment]
> Many thanks for this. If you could change that target of the PR the `development` branch rather than the `master` branch, it would be much easier to incorporate in the update cycle.

Thanks!

**Comment by mikebrady** [comment]
Thanks again for this. It builds with the latest Fedora and Ubuntu but they are on mbedtls version 2.28. Can you let me know where would I find a distribution with mbedtls 3, please?

**Comment by orangepizza** [comment]
I made this patch over openwrt master as it just moved mbedtls 3.6 few weeks ago, and I think you should be rolling release currently to get mbedtls3, its to be LTS 3.6 just released

**Comment by mikebrady** [comment]
Thanks. I found that the `alpine:edge` Docker image uses `mbedtls3` and your patches work on it.

**Pull request merged**
