### PR TITLE
Changed order of includes in shairport.c

### PR DESCRIPTION
**Pull request by pk2061**
I moved #include &lt;net/if.h&gt; after #include &lt;sys/socket.h&gt;
because the old order caused compilation errors like "error: field ‘ifru_addr’ has incomplete type" when I tried to compile with gcc-7.
This fixed it for me. Maybe this fix is useful to some else as well.

### CODE REVIEW

**Comment by mikebrady** [comment]
Thanks for the suggestion. Does it work on up-to-date compilers?

**Comment by pk2061** [comment]
I am afraid, that I do not have a quick way to test this in detail, but in my iMac running MacOS Big Sur and on my Raspberry Pi I had no issues setting this up, so I would guess I it should work on newer compilers.

**Comment by mikebrady** [comment]
Thanks. GCC on the Pi is at 8.3.0.

**Comment by mikebrady** [comment]
Hi @pk2061. If you don't mind, I'll respectfully decline your pull request. As you'll know, there's a lot happening on the `development` branch, so best leave things as they are. Maybe when things settle down, it might be worth checking on the `development` branch. 

Thanks for your interest in improving Shairport Sync.

**Comment by pk2061** [comment]
Hi Mike,

no worries.
Thanks for the feedback.

**Pull request closed without merging**
