### PR TITLE
Some issues found during the development of a DLNA backend

### PR DESCRIPTION
**Pull request by belboj**
During this year I've developed a new audio backend for shairport-sync that implements a simple DLNA (Digital Living Network Alliance) media server and media controller. With that software I can tell iTunes to play music on my stereo receiver, which supports DLNA but no Airport.

When I tested that software, I found a couple of issues, some of which are in the original source base from your repository. With this pull request I'd like to share my findings with you and propose fixes for them.

Is it okay for you to have one pull request for five small, but unrelated fixes at once, or do you prefer separate pull requests? And what about commit comments? I've added comprehensive, but not always short, explanations for all issues to the respective commit comments. I hope, they're enough to explain the problems, but please feel free to ask me if something is unclear.

### CODE REVIEW

**Comment by mikebrady** [comment]
Thanks for the pull request. Let me have a look through them and see if I can understand them all :)
BTW, would you be thinking of making the DNLA back end available?

**Comment by belboj** [comment]
Thanks that you accepted my pull request - and so quickly!

You hesitated on the `initstate()` matter, and I can understand that very well. For me, what happens doesn't make so much sense, either. It took me an lldb-Session with digging into the disassembly of initstate() to find out what caused the rare crash I had experienced.

The section of the man page you've cited tells us that `initstate()` returns the previous pointer, but that still doesn't mean that `initstate()` itself would dereference that old pointer. Just returning it would do no harm to shairport-sync, because `player_thread_func()` ignores the return value.

I've searched the web for the source code of the `initstate()` implementation that Apple uses. You can find it at https://opensource.apple.com/source/Libc/Libc-1244.1.7/stdlib/FreeBSD/random.c. The current state array is saved in the global variable `state` defined in line 222. `initstate()` sets `state` in line 403 to the given `arg_state`, albeit with a constant offset of `sizeof(uint32_t)`. Unfortunately, for some reason I don't quite understand, `initstate()` **writes** to the old state array in line 374 or 376 (and later once again to the new state array in line 407 or 409). In the version of `player_thread_func()` before my patch this meant it wrote to the location in memory, where the stack of the old player thread had been, and nobody knew what was there now. Then, anything could happen...

This may just be a bug in `initstate()`, but that is debatable. Writing to the old state array is certainly surprising, but the Posix standard doesn't explicitly forbid it.

Apart from that I agree to your last remark, that the `initstate()` call belongs somewhere to the application initialization phase rather than `player_thread_func()`.

**Comment by mikebrady** [comment]
Indeed you are correct, but the notion that `initstate()` might somehow hold on to that kind of information should have made me suspicious.!

**Comment by belboj** [comment]
In your first reaction you asked me if I wanted to publish my DLNA backend. While I don't object to that generally, I think that backend isn't mature enough for that (in contrast to shairport-sync in its current state, which works like a charm):
- The SSDP-Discovery-Phase isn't implemented. Usually, the controller should learn the URL of the audio device from UDP multicasts. In my current version, you have to configure it instead. But who knows how to use Wireshark to find that out first?
- I couldn't support it generally, because I've got only one DLNA hi-fi device available that I can test with, and only one version of iTunes that I happen to use currently. No chance to study the idiosyncrasies of other DLNA implementations, and I already know that my device has got some bugs and quirks.
- It is a bad fit for the primary goal of shairport-sync to provide synchronized audio output, because I cannot possibly synchronize DLNA. Therefore I copied the "N.B. no synchronisation -- so underflow or overflow is inevitable!" warning from the Audio Output backend.
- The output isn't perfect. There is some stuttering when I start to play and even some small cracks later that I have no explanation for yet.

**Comment by mikebrady** [comment]
Fair enough, thanks – no pressure.

**Pull request merged**
