### PR TITLE
Fixed race condition when stopping other threads with SIGUSR1

### PR DESCRIPTION
**Pull request by belboj**
I've got one other issue besides those in pull request #611, but this one is more complicated and more debatable, so I think it's better to open a separate pull request for it.

Many threads have got a main loop that checks some exit variable in the loop condition, e.g. `conn->please_stop`, `conn->timing_sender_stop` or `conn->stop`. To stop a thread, another thread sets that exit variable, sends a SIGUSR1 to that thread to get it out of blocking calls like `read()`, `write()` or `select()`, and finally joins it.

There is a hidden race condition though, a lost signal condition, which actually hit me several times: The signal wakes up the target thread only if it is actually blocked right now. If the target thread is currently executing some code outside the above mentioned system calls, it has got no effect. This is still fine if the thread is going to check the exit condition before the next blocking system call, but it fails if the signal arrives just after the check in the loop exit condition, but before the call to `read()` or similar. The section _Blocking Signals_ in http://www.linuxprogrammingblog.com/all-about-linux-signals has helped me to understand this issue better.

The only solution I know is to block SIGUSR1 until the blocking system call. Blocking a signal means that the signal is not delivered immediately, but postponed to the moment when you unblock it again. To be really thread-safe, unblocking the signal and blocking on a socket must be an atomic unit, so you can't do it yourself. You need a system call that provides this atomic unit, and AFAIK the only system in the Posix standard that provides this is `pselect()`. Therefore I propose a fix where every call to `read()`, `recv()`, `write()` and `sendto()` is prepended by a call to `pselect()` in a loop that checks the exit condition.

Unfortunately, this blows up the code and makes it less readable. And it requires that every function calling `read()`, `recv()`, `write()` or `sendto()` knows which exit variable it must check. Above all, I'm not convinced that I've corrected every such call. I actually left out some concerning metadata or the start and stop shell commands, because I was unsure what to do. So if you decide to merge this pull request, please double-check it first. Maybe you have got an idea how to solve that problem more elegantly?

### CODE REVIEW

**Comment by mikebrady** [comment]
Thanks for the request. Your analysis is right, I believe; there are certainly situations where the SIGUSR1 signal could be lost. 

As far as I can tell, (dangerous words these!) these issues have not caused any problems in use, except in the cases you report. So, while they should be fixed, of course, there is no mad rush, and time can be taken to ensure that the fixes work both theoretically and practically. It would be nice to be able to remove the use of SIGUSR1 signals completely – I've always thought that their use in this situation is a bit of a hack.

What about using using time-limited versions of the hitherto fully blocking calls. You can set a timeout on `recv` and on `send` and `sendto`, though I have not tried them out. Of course we would have to deal with incomplete transfers, etc., but then perhaps the extra code for each case could be put inside a function into which one would pass the address of the flag along with all the other stuff. What do you think yourself?

As a matter of interest, what are the issues around metadata and the start and stop shell commands that are puzzling you?

**Comment by belboj** [comment]
Alright, I'm not in a hurry either, especially because I have got a stop-gap solution that works for me.

In my patch I haven't added a `pselect()` instance before the `sendto()` in `metadata_process()`, but if I see it correctly right now, this function is executed by a thread that never exits, so there is no exit variable, right? And the `read()` in `command_start()` looks fine, because you execute it only if the config tells you to wait for some output? I haven't spent much time understanding this, so I simply kept my fingers off that.

I like your idea of time-limited send functions, because if sending blocks, you have got a serious problem in either the network or the receiver and you should probably treat that as an error. Furthermore, if you block sending a response you cannot receive a new query in the meantime and you appear unresponsive to clients. When you read, however, you are waiting for a request from a client and it's up the the client to decide if and when to send what commands. In this case I find it cleaner to block all the time instead of waking up periodically just in case some other thread has flipped the exit variable, unnecessarily consuming computing resources. Furthermore, the target thread wakes up immediately when it gets the signal; there is no timeout value causing an additional delay. Alas, the Posix signal API is arguably not the best API in the world and may be painful to use, so I can understand that you want to get rid of it.

You wrote you wanted to set a timeout on `recv()` and friends. I'm not sure how you want to do it, because in my Posix documentation and my man pages I haven't found a timeout parameter for these functions. Perhaps you can implement that yourself. As far as I can see, `non_blocking_write()` is already a function that implements blocking write with timeout if given a file descriptor of a socket in non-blocking mode. It could take an exit variable and/or a timeout value as an additional argument. Did you mean that?

**Comment by mikebrady** [comment]
Many thanks for your very thoughtful and comprehensive response. Reading though the code carefully, it seems to me that you have done a very thorough job of working out the best way to deal with the problem, so I'm very happy to take it in to Shairport Sync.

A couple of minor things – I was thinking of using `setsockopt()` for setting timers. Your point about using timers to effectively poll on the exit flags is well made. And I'm afraid you are right about the use of Posix signals – awkward but almost indispensable. It would be nice to hide some of the messy details inside functions, but it may not be worth the aggravation – better, perhaps, to add a few comments.

**Comment by mikebrady** [comment]
Many thanks!

**Comment by belboj** [comment]
Thank you for accepting my second pull request. I'm glad that you're happy and pleased with my work.

`setsockopt()` is a nice hint for me. I didn't know that there are standard socket options for timeouts, namely `SO_SNDTIMEO` and `SO_RCVTIMEO`. With these, it isn't necessary to switch the sockets to non-blocking mode as I did in my patch, although it should do no harm either. Perhaps, a combination of blocking mode sockets with `SO_SNDTIMEO` could even replace `non_blocking_write()` with a simple `write()`. But this is just an idea: there is actually no need to change the code in this respect.

**Pull request merged**
