### PR TITLE
pulseaudio: rewrite output

### PR DESCRIPTION
**Pull request by lrusak**
Hello!

I'm using the pulseaudio output for my system as I'm working on some network audio stuff with pulseaudio.

I found some limitations in the current design and took some time to help improve the interface (IMO).

I'll include the commit text:

>pulseaudio: remove delay function ceadb94
>this actually seems to do more harm than good. pulseaudio has an internal latency adjustment (which is already enabled for the stream). having two system trying to adjust latency isn't really a good idea.

>pulseaudio: rewrite output 9bfc661
this is a rewrite of the pulseaudio output. some major changes include:

>1) no more intermediate buffer
>2) cleaner structure with all globals contained in a struct
>3) ability to add more features in the future

>One main problem is that the playback thread seems to disappear when stopping playback. this can be a problem if we are waiting for the pulse mainthread and the lock never being removed. I've tried to cope with this by tracking the lock status but IMO this should be handled better by the application main thread.

I've also removed the hardcoded sample format and sample rate as those can be specified by the application.

I apologise for the single commit as I couldn't meaningfully break it up into smaller commits without breaking the build. If you need more clarification about a change just ask :smiley: 

I'm not sure if you have plans about how to improve the threading (to properly wait till the thread is in a good state) but that would help improve this output even more.

I've done some more work beyond this PR but I'll wait till this PR is accepted or not to PR those changes as I didn't want to overwhelm this PR.

The other changes are here: https://github.com/lrusak/shairport-sync/tree/meson-pulse-volume
They include:
1) pulseaudio latency adjustment (tested with network audio for latencies > 5 seconds)
2) pulseaudio volume control (still a bit WIP as it seem the db volume from this application is different than what pulseaudio wants so there is a non linearity to the volume control).

### CODE REVIEW

**Comment by mikebrady** [comment]
Hi there. Many thanks for this work, which must have taken quite a bit of time and effort.

So, first thing, would it be hard for you to target it to the `development` branch? Normally it would be preferable to road test it in the `developments branch before merging into the `master` branch.

Then, I’m sure lots of users would love to test it.  Speaking personally, I have never been a big user of PulseAudio, and so am not particularly skilled with it. So it would be great to check it out.

**Comment by lrusak** [comment]
> Hi there. Many thanks for this work, which must have taken quite a bit of time and effort.

I have a decent understanding of pulseaudio, so it wasn't too bad :smile: 

> So, first thing, would it be hard for you to target it to the `development` branch? Normally it would be preferable to road test it in the `development` branch before merging into the `master` branch.

Done :+1: 

> Then, I’m sure lots of users would love to test it. Speaking personally, I have never been a big user of PulseAudio, and so am not particularly skilled with it. So it would be great to check it out.

Let me know if you have any questions, When reviewing it may be better to look at the changes either side by side or just look at the new `audio_pa.c` as a whole.

I didn't really enforce any specific style, so if you see anything just let me know.

**Comment by mikebrady** [comment]
Thanks again.

**Comment by lrusak** [comment]
I would hold off on this until #1176 is resolved

**Comment by Manawyrm** [comment]
Thanks for your work on the PulseAudio support :smile: 
It already works better than the original pa output, but it's still not perfect for me (altough that might be a hardware thing, as it's running on an embedded system with low CPU power). 

Your branch `meson-pulse-volume` is not working, though: 
```
# shairport-sync -o pa -vvvv
Assertion 'pa_channels_valid(channels)' failed at pulse/volume.c:74, function pa_cvolume_set(). Aborting.
Aborted
```

**Comment by Manawyrm** [comment]
https://www.youtube.com/watch?v=-nv33D9c7l8

The Beatles have sounded better in the past... :sweat_smile: 
The same happens on my desktop using PulseAudio.

Any idea on what might be causing the distortion/buffer underruns? 
CPU usage also seems pretty high, shairport-sync + ALSA creates ~20% CPU load, shairport-sync + PA seems to be creating ~70-80% load.

**Comment by mikebrady** [comment]
Thanks for all the work and the reviewing and testing on this. I'd like to help with this, but right now I am really busy with another part of Shairport Sync.

**Comment by lrusak** [comment]
@Manawyrm thanks for testing! I have a couple comments.

This is currently what I'm using for starting pulseaudio (might not be correct but it's what I'm using on an RPi3)
```
/usr/bin/pulseaudio --system --disallow-exit --exit-idle-time=-1 --disable-shm --enable-memfd --realtime -vvv
```

When playing can you look at the logs and possibly see something like this?
```
journalctl -u pulseaudio | grep resampler.c

Mar 13 12:36:19 LibreELEC pulseaudio[1106]: I: [pulseaudio] resampler.c: Forcing resampler 'copy', because of fixed, identical sample rates.
Mar 13 12:36:19 LibreELEC pulseaudio[1106]: D: [pulseaudio] resampler.c: Resampler:
Mar 13 12:36:19 LibreELEC pulseaudio[1106]: D: [pulseaudio] resampler.c:   rate 44100 -> 44100 (method copy)
Mar 13 12:36:19 LibreELEC pulseaudio[1106]: D: [pulseaudio] resampler.c:   format float32le -> s16le (intermediate s16le)
Mar 13 12:36:19 LibreELEC pulseaudio[1106]: D: [pulseaudio] resampler.c:   channels 2 -> 2 (resampling 2)
```
(don't mind the old dates, it's from an old log).

You may see that pulseaudio is doing some resampling or not (ideally you don't want it to have to resample at all).

Short of that can you post your pulseaudio log when you try and play something? I'm wondering if the latency adjustment is going wild

**Comment by Manawyrm** [comment]
Hi,

so: Both my platforms (my desktop PC with a G933 headset) and my embedded audio streaming thingy are fixed to 48000 Hz, only (well, 96000 Hz would work as well, but that's not helping us here :smile: ). 
So I'll need PulseAudio to do resampling from 44100 -> 48000 in both cases. Maybe that's already causing the issue?

Here's a full PulseAudio log:
https://gist.github.com/Manawyrm/e6dfd748dfe88178022c6e781807b5c0

Here's a full Shairport-Sync log:
https://gist.github.com/Manawyrm/624aca81b4adcef8de84db2f06c7d86c

Yes, it's resampling: 
```
D: [pulseaudio] resampler.c: Resampler:
D: [pulseaudio] resampler.c:   rate 44100 -> 48000 (method speex-float-3)
D: [pulseaudio] resampler.c:   format s16le -> s16le (intermediate float32le)
D: [pulseaudio] resampler.c:   channels 2 -> 2 (resampling 2)
```
I'm guessing these issues might be reproducible on a normal machine by forcing PA to do 48000? (but I've not tested this yet).

```
# cat /etc/pulse/daemon.conf 
default-sample-format = s16le
default-sample-rate = 48000
avoid-resampling = yes
enable-remixing = yes
resample-method = speex-float-3

default-fragment-size-msec = 250
default-fragments = 16
```
(I've increased the default-fragment-size-msec in an attempt to solve the issue, but it doesn't change anything)

**Comment by lrusak** [comment]
The resample method may be pretty heavy for your hardware
```
resample-method = speex-float-3
```

you can see other resample methods using
```
# pulseaudio --dump-resample-methods
trivial
speex-float-0
speex-float-1
speex-float-2
speex-float-3
speex-float-4
speex-float-5
speex-float-6
speex-float-7
speex-float-8
speex-float-9
speex-float-10
speex-fixed-0
speex-fixed-1
speex-fixed-2
speex-fixed-3
speex-fixed-4
speex-fixed-5
speex-fixed-6
speex-fixed-7
speex-fixed-8
speex-fixed-9
speex-fixed-10
ffmpeg
auto
copy
peaks
soxr-mq
soxr-hq
soxr-vhq
```

using `trivial` or `speex-float-0` might help

**Comment by Manawyrm** [comment]
I'm not CPU-time limited on my desktop (where this also happens):

(this is recording the "Monitor of Device" input)

Playing other 44100 Hz content (with Pulse and resampling), through spotifyd, mpg123, etc. is no problem.

**Comment by lrusak** [comment]
I'll test out with another sample rate and see if I can reproduce the problem. In the mean time can you try setting a higher latency value here: https://github.com/mikebrady/shairport-sync/pull/1175/files#diff-028100dd23dd8c51eecb7e56ee1c83a842742e6bd314d4ab10a174b2b4178c28R278
it's set to 20ms which may not be enough, try setting it to 100ms (100000us)

Or you can test my auto latency adjustment branch here -> https://github.com/lrusak/shairport-sync/tree/pulse-latency

**Comment by Manawyrm** [comment]
Ah, hm. 
```
pa_usec_t latency = 200000;
```
makes it work fine!

I'll try with pulse-latency, next.

**Comment by Manawyrm** [comment]
... the pulse-latency branch behaves as follows: 
spews latency updated messages with increasing numbers, until it reaches ~21700000 (after 20s). Then it starts playing (with a big delay of course) and works fine.

**Comment by lrusak** [comment]
> ... the pulse-latency branch behaves as follows:
> spews latency updated messages with increasing numbers, until it reaches ~21700000 (after 20s). Then it starts playing (with a big delay of course) and works fine.

interesting, I'm not sure why it climbs so high (pulse should adjust it down as well). I may have to add a cap to that.

**Comment by Manawyrm** [comment]
Hm, not sure about that.
The latency will eventually (after minutes) go down to ~11s (and less), after which there's stuttering again. 

I've just limited the latency to 2s, after which it settles at ~1s (+-200ms). 
Audio sounds better, but will drop out after a while for a 100ms or so. This might be clock desync?

**Comment by lrusak** [comment]
> Hm, not sure about that.
> The latency will eventually (after minutes) go down to ~11s (and less), after which there's stuttering again.
> 
> I've just limited the latency to 2s, after which it settles at ~1s (+-200ms).
> Audio sounds better, but will drop out after a while for a 100ms or so. This might be clock desync?

Are you running some high latency setup? In my `pulse-latency` branch it will updated the latency if the reported latency changes by 5000us (5ms), so if you latency is jumping around a lot it's worth trying to increase that value which can be found here https://github.com/lrusak/shairport-sync/commit/5582099448d67c738ac93e9d77fa88e368b6a1bb#diff-028100dd23dd8c51eecb7e56ee1c83a842742e6bd314d4ab10a174b2b4178c28R160

I've tested it with network audio over wireless and I need about `25000 - 40000` so it doesn't jump around too much

**Comment by Manawyrm** [comment]
Hm, no I'm running a pretty much ideal setup: high quality WiFi AP for the phone, ethernet for the machine with shairport-sync. 

@TobleMiner did some digging around and changed some things, but we couldn't get it to work perfectly either:
https://github.com/Manawyrm/shairport-sync/commit/9ebdf376902a642d1d31105541b0852242a183c5
shairport will write too many samples into the buffer, which PulseAudio isn't expecting / causes lost samples. 

This also has a prototype delay estimation (currently commited out in the last few lines). 
There's still a noticable "click" every few seconds (i guess when there's a overflow due to clock desync?), but it's behaving somewhat better now.

**Comment by lrusak** [comment]
@Manawyrm I pushed changes to my [pulse-latency](https://github.com/lrusak/shairport-sync/tree/pulse-latency) branch, it should work much better now. Would you mind giving it another test?

**Comment by Manawyrm** [comment]
@lrusak Awesome! The current pulse-latency branch works flawlessly on all of my devices, low CPU utilization, stutter-free audio, A/V in sync. Thanks! :smile: 

... are you going to open another PR for this or move your changes into this pull request?

**Comment by lrusak** [comment]
> @lrusak Awesome! The current pulse-latency branch works flawlessly on all of my devices, low CPU utilization, stutter-free audio, A/V in sync. Thanks! 
> 
> ... are you going to open another PR for this or move your changes into this pull request?

I'd rather open another PR for that. For this PR I'll change the default latency to 100ms as that should be a good default until the latency PR.

There is still the outstanding change #1176 which I would like to solve before merging this.

**Comment by mikebrady** [comment]
Hello again. Still trying to figure out how to bring this into Shairport Sync safely.

So I have an idea. Could you modify it slightly so that it can be built as a separate PulseAudio back end that would be built under a new `--with-` flag, e.g. `--with-pax`.

That way, people could test it out as an alternative, and if there were any big problems they could switch to the existing one.

Then, after a while, if there were no big "gotchas" it could replace the existing one. What do you think?

**Comment by lrusak** [comment]
Sorry for the delay, we recently had a baby so I don't have much time right now.

I'd still like to try and fix this so I don't need to use #1176, however I don't know when I'll have time to do that.

**Comment by mikebrady** [comment]
@lrusak, thanks for the update, and congratulations on the new baby 🎉.
We might park this Pull Request for the time being. Many thanks.

**Pull request closed without merging**
