### PR TITLE
Update Dockerfiles to Alpine 3.17 and set fixed startup order

### PR DESCRIPTION
**Pull request by yubiuser**
This PR archives two goals. 
1) It updated the underlying Alpine images  to the current versions v3.17 and adjusts necessary packages to successfully build and run `shairport-sync`
2) It sets a fixed "startup" order for the services started by s6. I discovered, while working on the images, that no specific startup order was used (but maybe tried with the naming schema?) leading to failures as some services depend on others (e.g. `shairport-sync` on `avahi`. The startup order is set by creating a file called `dependencies` in the respective folder and setting the previous service as dependency. I set the `startup.sh` as being the first service to start and added `shairport-sync` as service for `s6`. The order is now
  - 1 `startup.sh`
  - 2 `dbus`
  - 3 `avahi`
  - 4 (`nqptp`)
  - 5 `shairport-sync`
s6 considers a service as being started when the `run` file is executed, but sometimes the actual service needs a bit longer to be up and running. That's why `avahi` and `shairport-sync` check for actual presence of `PID` files as well.

P.S. This PR looks bigger than it is. Most is due to renaming all files/folders because I added `01` prefix to `startup.sh`

____

Old startup sequence (for "classic"). (E.g. See `STARTING - Wed Feb  1 13:14:16 UTC 2023` coming after ` Stating dbus`)
```
s6-rc: info: service 02-avahi: starting
s6-rc: info: service 01-dbus: starting
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service 02-avahi successfully started
s6-rc: info: service 01-dbus successfully started
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service startup: starting
Starting dbus
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
STARTING - Wed Feb  1 13:14:16 UTC 2023
s6-rc: info: service startup successfully started
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service syslogd-prepare: starting
s6-rc: info: service syslogd-prepare successfully started
s6-rc: info: service syslogd-log: starting
s6-rc: info: service syslogd-log successfully started
s6-rc: info: service syslogd: starting
s6-rc: info: service syslogd successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Starting avahi
Found user 'avahi' (UID 86) and group 'avahi' (GID 86).
Successfully dropped root privileges.
avahi-daemon 0.8 starting up.
WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
Loading service file /etc/avahi/services/sftp-ssh.service.
Loading service file /etc/avahi/services/ssh.service.
*** WARNING: Detected another IPv4 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***
*** WARNING: Detected another IPv6 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***

...

Server startup complete. Host name is ThinkPad-X230.local. Local service cookie is 3277534057.
```

New startup sequence
```
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service syslogd-prepare: starting
s6-rc: info: service 01-startup: starting
STARTING - Wed Feb  1 13:07:07 UTC 2023
s6-rc: info: service 01-startup successfully started
s6-rc: info: service 02-dbus: starting
s6-rc: info: service 02-dbus successfully started
s6-rc: info: service 03-avahi: starting
Starting dbus
s6-rc: info: service 03-avahi successfully started
s6-rc: info: service 04-shairport-sync: starting
s6-rc: warning: dbus is not running, sleeping for 1 seconds before trying to start avahi
s6-rc: info: service 04-shairport-sync successfully started
s6-rc: warning: avahi is not running, sleeping for 1 seconds before trying to start shairport-sync
s6-rc: info: service syslogd-prepare successfully started
s6-rc: info: service syslogd-log: starting
s6-rc: info: service syslogd-log successfully started
s6-rc: info: service syslogd: starting
s6-rc: info: service syslogd successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Starting avahi
s6-rc: warning: avahi is not running, sleeping for 1 seconds before trying to start shairport-sync
Found user 'avahi' (UID 86) and group 'avahi' (GID 86).
Successfully dropped root privileges.
avahi-daemon 0.8 starting up.
WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
Loading service file /etc/avahi/services/sftp-ssh.service.
Loading service file /etc/avahi/services/ssh.service.
*** WARNING: Detected another IPv4 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***
*** WARNING: Detected another IPv6 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***

...

Server startup complete. Host name is ThinkPad-X230.local. Local service cookie is 2544304336.
Starting shairport-sync
```

### CODE REVIEW

**Comment by mikebrady** [comment]
Thanks for the suggestion -- we'll take a look at it!

**Comment by yubiuser** [comment]
I pushed a commit:

1) `ENTRYPOINT [ "/init" ]` is not necessary, as `crazymax/alpine-s6` sets this by default. https://github.com/crazy-max/docker-alpine-s6#usage

2) I figured, moving `/shairport-sync` from the `ENTRYPOINT` to a dedicated `s6` service broke the option to pass command line arguments. This is fixed by calling `shairport-sync` within the `run` with an argument (`$ARG`) to which is has access via the `with-contenv` environment. The docker command line call can pass all arguments now with `-e ARG="xzy"`. I changed the documentation. 
(Not sure where the documentation of https://hub.docker.com/r/mikebrady/shairport-sync resides. It will need the changes too)

**Comment by mikebrady** [comment]
Am I right in thinking that the second commit turns Shairport Sync into a supervised service, and that if it exits or crashes, it will be automatically restarted by the s6 system? If so, that's actually undesirable: we want the image to exit when Shairport Sync exits so that the host can maybe do something about the problem, if there is one... For example, if the output device suddenly disappears, it would be right for the image to exit.

**Comment by yubiuser** [comment]
> Am I right in thinking that the second commit turns Shairport Sync into a supervised service, and that if it exits or crashes, it will be automatically restarted by the s6 system?

True for the first part, false for the second part: it turns Shairport Sync into a supervised service to guarantee the startup order. However, there is a `finish` file in `05-shairport-sync` that will be executed when SPS fails/crashes and executes `bin/halt` to stop the container.
https://github.com/just-containers/s6-overlay#writing-an-optional-finish-script

**Comment by mikebrady** [comment]
Great stuff, thanks. I’m rather anxious to avoid `-e …` stuff if possible. I don’t suppose we are (or can be) guaranteed that the `CMD` waits until everything is ready?

**Comment by yubiuser** [comment]
> I don’t suppose we are (or can be) guaranteed that the CMD waits until everything is ready?

The `CMD` is executed after all services are started, **however** starting a service and having everything available for subsequent services/commands are two different things. (This is why we need to check if `*.pid` files are present). Running `shairport-sync` straight as `CMD` will fails as `avahi` and `dbus`might not be ready. But I found a solution and will push an update. This will also avoid `-e`

**Comment by yubiuser** [comment]
I've set a `run.sh` script as second `ENTRYPOINT` which allows to pass arguments as usual. The script will keep the check for the presence of the relevant `*.pid` file.

**Comment by mikebrady** [comment]
Thanks for this.

**Pull request merged**
