### PR TITLE
2 audio filters added, a volume-dependent-loudness and a convolution filter

### PR DESCRIPTION
**Pull request by yannpom**
Hello Mike,

Following "issue" #480, here the code that integrates both filters. It works great on my Raspberry Pi.

What would be even better would be a way to activate/deactivate them on the fly, so we can hear the before/after. Any suggestion on how I could interact live with an instance of shairport-sync? I was thinking about using a simple read from stdin, or ncurses to make it a bit more sexy, or even some simple http frontend like https://github.com/cesanta/mongoose, but that might be overkill.

The convolution part, using C++, must be activated with `--with-convolution` during `./configure`.

I put some documentation in `script/shairport-sync.conf`.

### CODE REVIEW

**Comment by mikebrady** [comment]
Hi @yannpom yannpom, and thanks for this great work. Regarding a front end, I think a D-Bus interface might be a solution – after all, the app is to all intents and purposes a daemon. You might see that, in another small repository, I'm working on some very simple D-Bus stuff to try to get the hang of it. But it looks like a standard and general purpose solution to this and other pinch points in the app. What do you think?

I'm going to try this out locally for a short while before I merge it, if that's okay?

**Comment by mikebrady** [comment]
Hello again. I'm getting a few error reports. I guess you have a compiler setting or something like that that isn't in the original? Here they are anyway:

```
In file included from FFTConvolver/AudioFFT.cpp:22:0:
FFTConvolver/AudioFFT.h:103:24: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
       AudioFFTImpl() = default;
                        ^
FFTConvolver/AudioFFT.h:104:33: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
       virtual ~AudioFFTImpl() = default;
                                 ^
FFTConvolver/AudioFFT.h:110:43: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
       AudioFFTImpl(const AudioFFTImpl&) = delete;
                                           ^
FFTConvolver/AudioFFT.h:111:54: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
       AudioFFTImpl& operator=(const AudioFFTImpl&) = delete;
                                                      ^
FFTConvolver/AudioFFT.h:161:10: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
     std::unique_ptr<details::AudioFFTImpl> _impl;
          ^
FFTConvolver/AudioFFT.h:163:33: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
     AudioFFT(const AudioFFT&) = delete;
                                 ^
FFTConvolver/AudioFFT.h:164:44: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
     AudioFFT& operator=(const AudioFFT&) = delete;
                                            ^
In file included from FFTConvolver/FFTConvolver.h:21:0,
                 from FFTConvolver/convolver.cpp:5:
FFTConvolver/AudioFFT.h:103:24: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
       AudioFFTImpl() = default;
                        ^
FFTConvolver/AudioFFT.h:104:33: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
       virtual ~AudioFFTImpl() = default;
                                 ^
FFTConvolver/AudioFFT.h:110:43: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
       AudioFFTImpl(const AudioFFTImpl&) = delete;
                                           ^
FFTConvolver/AudioFFT.h:111:54: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
       AudioFFTImpl& operator=(const AudioFFTImpl&) = delete;
                                                      ^
FFTConvolver/AudioFFT.h:161:10: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
     std::unique_ptr<details::AudioFFTImpl> _impl;
          ^
FFTConvolver/AudioFFT.h:163:33: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
     AudioFFT(const AudioFFT&) = delete;
                                 ^
FFTConvolver/AudioFFT.h:164:44: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
     AudioFFT& operator=(const AudioFFT&) = delete;
                                            ^
In file included from FFTConvolver/FFTConvolver.h:21:0,
                 from FFTConvolver/FFTConvolver.cpp:18:
FFTConvolver/AudioFFT.h:103:24: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
       AudioFFTImpl() = default;
                        ^
FFTConvolver/AudioFFT.h:104:33: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
       virtual ~AudioFFTImpl() = default;
                                 ^
FFTConvolver/AudioFFT.h:110:43: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
       AudioFFTImpl(const AudioFFTImpl&) = delete;
                                           ^
FFTConvolver/AudioFFT.h:111:54: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
       AudioFFTImpl& operator=(const AudioFFTImpl&) = delete;
                                                      ^
FFTConvolver/AudioFFT.cpp:99:36: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11
       virtual void init(size_t size) override
                                    ^
FFTConvolver/AudioFFT.cpp:114:63: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11
       virtual void fft(const float* data, float* re, float* im) override
                                                               ^
FFTConvolver/AudioFFT.cpp:139:70: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11
       virtual void ifft(float* data, const float* re, const float* im) override
                                                                      ^
FFTConvolver/AudioFFT.cpp:742:35: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
       OouraFFT(const OouraFFT&) = delete;
                                   ^
FFTConvolver/AudioFFT.cpp:743:46: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
       OouraFFT& operator=(const OouraFFT&) = delete;
                                              ^
FFTConvolver/AudioFFT.cpp:87:11: error: looser throw specifier for ‘virtual audiofft::details::OouraFFT::~OouraFFT()’
     class OouraFFT : public AudioFFTImpl
           ^
In file included from FFTConvolver/AudioFFT.cpp:22:0:
FFTConvolver/AudioFFT.h:104:15: error:   overriding ‘virtual audiofft::details::AudioFFTImpl::~AudioFFTImpl() throw ()’
       virtual ~AudioFFTImpl() = default;
               ^
FFTConvolver/AudioFFT.h:161:10: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
     std::unique_ptr<details::AudioFFTImpl> _impl;
          ^
FFTConvolver/AudioFFT.h:163:33: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
     AudioFFT(const AudioFFT&) = delete;
                                 ^
FFTConvolver/AudioFFT.h:164:44: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
     AudioFFT& operator=(const AudioFFT&) = delete;
                                            ^
FFTConvolver/AudioFFT.cpp:746:10: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
     std::unique_ptr<AudioFFTImpl> MakeAudioFFTImpl()
          ^
FFTConvolver/AudioFFT.cpp: In constructor ‘audiofft::AudioFFT::AudioFFT()’:
FFTConvolver/AudioFFT.cpp:989:5: error: class ‘audiofft::AudioFFT’ does not have any field named ‘_impl’
     _impl(details::MakeAudioFFTImpl())
     ^
FFTConvolver/AudioFFT.cpp:989:11: error: ‘MakeAudioFFTImpl’ is not a member of ‘audiofft::details’
     _impl(details::MakeAudioFFTImpl())
           ^
FFTConvolver/AudioFFT.cpp: In member function ‘void audiofft::AudioFFT::init(size_t)’:
FFTConvolver/AudioFFT.cpp:997:5: error: ‘_impl’ was not declared in this scope
     _impl->init(size);
     ^
FFTConvolver/AudioFFT.cpp: In member function ‘void audiofft::AudioFFT::fft(const float*, float*, float*)’:
FFTConvolver/AudioFFT.cpp:1003:5: error: ‘_impl’ was not declared in this scope
     _impl->fft(data, re, im);
     ^
FFTConvolver/AudioFFT.cpp: In member function ‘void audiofft::AudioFFT::ifft(float*, const float*, const float*)’:
FFTConvolver/AudioFFT.cpp:1009:5: error: ‘_impl’ was not declared in this scope
     _impl->ifft(data, re, im);
     ^
FFTConvolver/convolver.cpp: In function ‘void convolver_init(const char*, int)’:
FFTConvolver/convolver.cpp:24:106: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
     die("Impulse file \"%s\" sample rate is %d Hz. Only 44100 Hz is supported", filename, info.samplerate);
                                                                                                          ^
FFTConvolver/convolver.cpp:27:103: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
     die("Impulse file \"%s\" contains %d channels. Only 1 or 2 is supported.", filename, info.channels);
                                                                                                       ^
FFTConvolver/convolver.cpp:54:103: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   debug(1, "IR initialized from \"%s\" with %d channels and %d samples", filename, info.channels, size);
```

**Comment by yannpom** [comment]
You are right, here is the config line I use for cross compiling for my Raspberry Pi:

```
PKG_CONFIG_PATH=/Users/yann/Documents/RPI/usr/lib/pkgconfig \
CC=/usr/local/linaro/arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-gcc \
CXX=/usr/local/linaro/arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-g++ \
CFLAGS="--sysroot=/Users/yann/Documents/RPI -mcpu=cortex-a7 -mfloat-abi=hard -mfpu=vfpv4" \
CXXFLAGS="--sysroot=/Users/yann/Documents/RPI -mcpu=cortex-a7 -mfloat-abi=hard -mfpu=vfpv4 -std=c++11 -O2" \
LDFLAGS="--sysroot=/Users/yann/Documents/RPI -pthread" \
./configure --host arm-linux-gnueabihf-raspbian --with-avahi --with-alsa --with-ssl=openssl --with-soxr --with-convolution
```

There are `-std=c++11` and `-O2` in my `CXXFLAGS`. The FFTConvolver code I used (https://github.com/HiFi-LoFi/FFTConvolver) needs C++11.

I also did some quick benchmarks on my Raspberry Pi 2 with both filters activated:

Flags | Both filters | Loudness only | None
------|------------|---------------|-------
no flags   | 110 % |  28%  | 26%
AM_CXXFLAGS=-O2 | 54% | 28% | 26%
AM_CXXFLAGS=-O2 && AM_CFLAGS=-O2 | 37 % | 10% | 10%

I think `-O2` should be added to both `AM_CFLAGS` and `AM_CXXFLAGS`. Would there be a reason not to let GCC optimise the code?

Even with no filters, the speed up with `-O2` is x2.6!

**Comment by yannpom** [comment]
I hope you can build successfully now?
I have no experience with D-Bus, I'll start digging to see what could be done :)

**Comment by yannpom** [comment]
And sure you can keep this pull request opened before merging it. I still need to update the `README.md` with some description about those filters.

**Comment by mikebrady** [comment]
Thanks for all this. I put up a small D-Bus repository, you might find it helpful, as getting documentation is hard.

AFAIK, there is no reason not to have -O2 (how about Os or O3 – are they any better?). The only reason for -O0 is for debugging.

**Comment by mikebrady** [comment]
It compiles now, thanks – just a couple of warnings:
```
FFTConvolver/convolver.cpp: In function ‘void convolver_init(const char*, int)’:
FFTConvolver/convolver.cpp:24:106: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
```

**Comment by yannpom** [comment]
I know about this warning. It is not directly related to this new code, but it is because `die()` method wants a `char*` and we're passing a string literal. `die()` should ask for a `const char *`. There is no warning in `C` but there is one in `C++`.

I'm pushing the change in `common.h` and `common.c`.

**Comment by mikebrady** [comment]
Thanks again. One further little thing. It is looking for an impulse response file:
```
Feb 28 11:47:31 ubuntu shairport-sync[101576]: Support for the Apple ALAC decoder has not been compiled into this version of Shairport Sync. The default decoder will be used.
Feb 28 11:47:31 ubuntu shairport-sync[101576]: Convolution enabled but no convolution_ir_file provided
Feb 28 11:47:31 ubuntu systemd[1]: shairport-sync.service: Main process exited, code=exited, status=1/FAILURE
Feb 28 11:47:31 ubuntu systemd[1]: shairport-sync.service: Unit entered failed state.
Feb 28 11:47:31 ubuntu systemd[1]: shairport-sync.service: Failed with result 'exit-code'.
```

**Comment by yannpom** [comment]
Here you have a database with some IR files: http://www.openairlib.net/auralizationdb

Using one of those would simulate the acoustic of, let's say a church, in your living room. That's one use of the convolution with IR. But my use is the opposite: use this mathematical convolution to apply an inverse IR. Well, I should provide more information in the `README.md` on how to generate an IR that suits your speaker+room.

But for testing purposes that works. Note that they are provided @ 48kHz and should be converted to 44100 Hz. I have one ready to go here: https://b.ouisnap.com/upload/lyd3_000_ortf_44100.wav
You should end up with a lot of echo in your sound as it's an IR from a church.

Here is my configuration file:
```
general =
{
	name = "HifiBerryALSA";
	output_backend = "alsa";
	interpolation = "soxr";
}
alsa =
{
	output_format = "S32";
}
dsp =
{
	convolution = "yes";
	convolution_ir_file = "lyd3_000_ortf_44100.wav";
	convolution_gain = -4;
	convolution_max_length = 44100;

	loudness = "yes";
	loudness_reference_volume_db = -20;
}
```

**Comment by mikebrady** [comment]
Great. And where should the IR file be placed? (Sorry if I'm being a bit dense here...)

**Comment by yannpom** [comment]
You can either use an absolute path, or a path relative to shairport-sync running directory ;-)

**Comment by mikebrady** [comment]
Thanks again. I'll give it a try. I wonder if it's time to have a specific folder for Shairport Sync stuff – e.g. `/etc/shairport-sync`, containing a configuration file, say `main.conf` and a subdirectory called, say, `effects` which would contain named convolution files, like `church.wav` and so on?

**Comment by yannpom** [comment]
Thank you for the merge Mike.

But I'm not finished on this one ;-) I'll add some documentation in the main README file. And I also want a quick way to switch between different convolution filters, with a keyboard key, to do some kind of blind test during the tuning of the filter. Maybe I will follow your idea and use D-Bus to expose some shairport-sync internal parameters, then write a python script to remote control it. I don't know yet :)

I was previously creating my filters with [Room EQ Wizard](http://www.roomeqwizard.com) but I'm currently experimenting with [DRC-FIR](http://drc-fir.sourceforge.net) that does more than just correcting the amplitude.

You can have a look at the documentation example to see what's achievable with DRC-FIR [HERE](http://drc-fir.sourceforge.net/doc/drc.html#htoc237). It does correct quite well the phase and amplitude (figure 21 to 34), but not only, some impressive results are also visible in the spectral decay (figure 35 to 58).

**Comment by mikebrady** [comment]
That's fine, Yann (?) – it's the `development` branch, so it's okay to put stuff that's interesting and good but not finished. The housekeeping side of it needs some attention too, and it'll take a little time.

I'll certainly have a look at the references you've given.

**Comment by lx-pin** [comment]
Dear Mike,
First of all thank you for your work . 
being a noob in linux i am looking for kind of step-by-step manual (maybe Yann could help here) how to set up rpi (2b in my case) as a 2 channel airplay receiver with fir filtering (or at least several bands parametric eq) for room correction purposes.
I spend so many hours of attempts and reinstalls of rasbpian and now decided to wright Here.
Thank you in advance!

**Comment by jshep321** [comment]
Hi @yannpom.  

Do you have a link how to create the IR file from REW?  I'm a noob with REW and currently awaiting my backordered calibrated mic.

I see how to export the eq settings but not a .wav file.  

Thanks!

**Pull request merged**
