### PR TITLE
Makefile.am: allow building and installing from a separate build directory (version 2)

### PR DESCRIPTION
**Pull request by lrusak**
Ok this is an updated version of #1493 

I think I got all the renames now.

The one thing I did notice is that before if the systemd or systemv services existed they didn't get updated, I'm not sure why that is? If you want that behaviour still just say so and I can add it in. It seems odd to me though.

Please let me know if you want anything changed before merging.

example install
```
$ tree install
install
├── etc
│   ├── dbus-1
│   │   └── system.d
│   │       ├── shairport-sync-dbus.conf
│   │       └── shairport-sync-mpris.conf
│   ├── shairport-sync.conf
│   └── shairport-sync.conf.sample
└── usr
    ├── bin
    │   └── shairport-sync
    └── lib
        └── systemd
            └── system
                └── shairport-sync.service
```

### CODE REVIEW

**Comment by mikebrady** [comment]
Thanks again for your work on this. 

> The one thing I did notice is that before if the `systemd` or System V services existed they didn't get updated, I'm not sure why that is? 

This is for two reasons:
1. If the service file already exists, there is no point in replacing it during an update. Related to this in the `systemd` case, replacing the service file causes the system to complain when you restart the service without running `systemctl daemon-reload` first.
2. If the service file already exists, it may have been customised by the user. For example, the user may have added a command line argument to the startup command.

The only time this approach causes problems is when the service file supplied with Shairport Sync actually changes. In that situation, the user has to manually remove the older one.

**Comment by lrusak** [comment]
It would probably be good to install the systemd service into `/usr/lib/systemd/system` then where it isn't expected to be edited.

Then anyone changing the service using `systemctl edit shairport-sync` will have edits in `/etc/systemd/system/`

**Comment by lrusak** [comment]
For the sake of simplicity I've adjusted the behaviour so that it only installs the systemd, systemv, and cygwin services if they don't exist (like was the behaviour before this PR).

**Comment by charlesomer** [comment]
Hi @lrusak, have you tested this with the `--with-airplay-2` flag? It looks like it might fail, or I could be doing something wrong when updating the docker file for these changes :)

**Comment by lrusak** [comment]
> Hi @lrusak, have you tested this with the `--with-airplay-2` flag? It looks like it might fail, or I could be doing something wrong when updating the docker file for these changes :) 

Can you tell me what is failing, I'm not sure what in these changes would be related to airplay2?

**Comment by charlesomer** [comment]
```
plist_xml_strings.h: plists/get_info_response.xml
	echo "// Do not edit!" > plist_xml_strings.h
	echo "// This file is automatically generated from files in the plists folder." >> plist_xml_strings.h
	echo "" >> plist_xml_strings.h
	xxd -i plists/get_info_response.xml >> plist_xml_strings.h
	echo "" >> plist_xml_strings.h
plist_xml_strings.c: plist_xml_strings.h
	touch plist_xml_strings.c
```

This part I believe, this is the docker build error:
```
 > [builder 24/28] RUN make -j $(nproc):
#0 0.518 echo "// Do not edit!" > plist_xml_strings.h
#0 0.523 gdbus-codegen --interface-prefix org.gnome --generate-c-code dbus-interface ../org.gnome.ShairportSync.xml
#0 0.528 gdbus-codegen --interface-prefix org.mpris --generate-c-code mpris-interface ../org.mpris.MediaPlayer2.xml
#0 0.543 echo "// This file is automatically generated from files in the plists folder." >> plist_xml_strings.h
#0 0.566 echo "" >> plist_xml_strings.h
#0 0.585 xxd -i plists/get_info_response.xml >> plist_xml_strings.h
#0 0.611 xxd: plists/get_info_response.xml: No such file or directory
#0 0.613 make: *** [Makefile:1631: plist_xml_strings.h] Error 2
#0 0.614 make: *** Waiting for unfinished jobs....
------
error: failed to solve: executor failed running [/bin/sh -c make -j $(nproc)]: exit code: 2
```

So I guess it needs to work out where the `plists/get_info_response.xml` file is somehow? :)

**Comment by lrusak** [comment]
@charlesomer were you building with this PR and in a separate build dir?

I pushed a fixup commit (to be squashed) to fix building with `--with-airplay-2` when built in a separate directory.

**Comment by charlesomer** [comment]
That fix seems to work :) I've also noticed that the version seems to be missing (`4.1-dev-AirPlay2`, should include another number before "AirPlay2"). Is this the same for you when building in a separate folder?

**Comment by lrusak** [comment]
> That fix seems to work :) I've also noticed that the version seems to be missing (`4.1-dev-AirPlay2`, should include another number before "AirPlay2"). Is this the same for you when building in a separate folder?

@charlesomer I don't think so? I seem to get the same version number building my branch as I do with the development branch, (with or without a separate build dir).

```
4.1-dev-AirPlay2-OpenSSL-Avahi-pw-metadata-dbus-mpris-sysconfdir:/etc
```

I did add an extra fixup to fix the git versioning, but I'm not sure if that's relevant.

**Comment by charlesomer** [comment]
I think it’s supposed to look something like this: `4.1-dev-433-g82ce9d76-dirty-AirPlay2-alac`?

**Comment by lrusak** [comment]
> I think it’s supposed to look something like this: `4.1-dev-433-g82ce9d76-dirty-AirPlay2-alac……..`?

Yea that will be fixed by the git version fix I pushed.

**Comment by charlesomer** [comment]
I think that’s intentional to make it easy to determine which version of SPS people are running if they run into issues. Or have I missed something? 😄

**Comment by lrusak** [comment]
> I think that’s intentional to make it easy to determine which version of SPS people are running if they run into issues. Or have I missed something? 😄

I'm not sure what you are asking?

**Comment by charlesomer** [comment]
I don't think it needs to be fixed, I think it's intentional - @mikebrady ?

**Comment by lrusak** [comment]
> I don't think it needs to be fixed, I think it's intentional - @mikebrady ?

Sorry, I mean I fixed that from being missing in the latest fixup.

**Comment by lrusak** [comment]
rebased and squashed the fixups

**Comment by mikebrady** [comment]
Thanks again. We’ll take a look over the next week or so.

**Comment by mikebrady** [comment]
Hi Lukas. Still looking at this, thanks. As a matter of interest, what was your motivation for this -- in other words, why was it important to be able to build and install from a separate directory?

**Comment by mikebrady** [comment]
Hello again. The changes seem to work now on a standard build and with Docker, thanks. I'll test it on FreeBSD a little later this week, when I'll have access to a machine.

**Comment by mikebrady** [comment]
Hi Lukas. I merged this a few hours ago by accident -- I had intended to commit a very small change but this merge was in the code. Anyway, it seems to be working fine on Linux and on the Docker images -- I still have to check it for FreeBSD. Thanks again.

**Pull request merged**
