### PR TITLE
Automated docker build (start).

### PR DESCRIPTION
**Pull request by charlesomer**
Contains automatic docker builds using GitHub Actions.

For now, these are only triggered on the 'development' branch to get people up and running with the early AirPlay 2 work.

Automatic building from 'master' will be added later along with on a version release.

### CODE REVIEW

**Comment by charlesomer** [comment]
Hold for now.

**Comment by charlesomer** [comment]
Should be okay now 👍

**Comment by noelhibbard** [comment]
Thanks for this, I tried to modify Mike's docker to build for AP2 but couldn't find all the right alpine package names to satisfy the build reqs. I finally gave up and switched to Debian.

**Comment by charlesomer** [comment]
No worries :) Yeah the latest alpine images have packages which are _too_ new compared to the current ones for Debian so for now we've pinned the docker image to a version. I'll post when this is merged and the image is being pushed to Docker Hub 👍

**Pull request merged**
