### PR TITLE
ci: build docker with pipewire

### PR DESCRIPTION
**Pull request by irdkwmnsb**
Working on top of #1642 I really needed a pipewire way of running this on my server

Thankfully adding it was not hard

One more thing I would do is move docker-compose.yaml to docker-compose.example.yaml, since most users would need to modify the file to fit their needs

### CODE REVIEW

**Comment by mikebrady** [comment]
Many thanks for this. A question I have is how much bigger the runtime Docker image gets with the PipeWire dependencies. Would you have any idea?

**Comment by irdkwmnsb** [comment]
> Many thanks for this. A question I have is how much bigger the runtime Docker image gets with the PipeWire dependencies. Would you have any idea?

On my machine building the image yields 170MBs with pipewire against 162MB without it

**Comment by mikebrady** [comment]
Very useful, thanks!

**Comment by mikebrady** [comment]
Many thanks for this. I note it's only for the AirPlay 2 image, but let's see how it goes before bringing it to the Classic image.

**Pull request merged**
