### PR TITLE
constant 0x100000000 should be 0x100000000LL to avoid warning

### PR DESCRIPTION
**Pull request by jief666**
To avoid warning, thanks.

### CODE REVIEW

**Comment by mikebrady** [comment]
Hi there. Thanks for this. What machine are you building for when this happens, please?

**Comment by jief666** [comment]
ARM 32 bits, with stdout backend (no alsa).
I redirected stdout in a file. The file content look strange, mostly 00 and FF. After further testing in few days, can I get back to you if I need help ?

**Comment by mikebrady** [comment]
Thanks. I am not getting the warning. The problem I have with your suggestion is that it's not necessarily always the case that a `long long` is 64 bits.

I just tried:
```
frame_difference =
              (uint64_t)reference_timestamp + (uint64_t)0x100000000 - (uint64_t)play_segment_reference_frame;
```
and I got no warning from that.

Can you try it – if it works, it would seem more  consistent. What do you think?

**Comment by jief666** [comment]
I tried that first hand, but still got the warning. The constant is built
before the cast. If the compiler have default constant as int 32 bits,
you'll get the warning even if there is cast after.
You probably have 64 bits int default compiler, haven't you ?
What long long could be else that 64 bits ? From the spec, it can only be
more, which is not a problem, is it ?

**Comment by mikebrady** [comment]
Thanks. I'm using the standard compiler that comes with Jessie on the Raspberry PI, which is a 32-bit machine. I don't know what the default int on it is, but if I had to guess, I'd say is was 32 bits.

The `long long` could in theory be bigger than 64 bits. So, putting in an LL seems to me to be fixing a warning by putting in something that is explicitly wrong – in other words, a hack.

Is it possible that there is something strange about the compiler setup are you using?

**Comment by mikebrady** [comment]
Update – maybe you could tall me what compiler flags you're using...

**Comment by jief666** [comment]
Definitely nothing strange : gcc 4.4.

From this page :
http://stackoverflow.com/questions/3542040/cannot-assign-a-value-to-64-bit-integer-on-32-bit-platform,
I thought the culprit would be compiling in C89 instead of C89. But
compiling in C99 give some undefined errors that should be corrected anyway.

Still, the UINT64_C(0x100000000) works in C89 (it's not a cast but a
macro). So far it adds ULL behind the constant, but it would be adapted for
each plateform and seems to be the right answer, plateform independant.

**Comment by mikebrady** [comment]
Thanks for the information and for the reference – very interesting! (This is what's great about open source.)

So, I tried the UINT64_C() idea and it works for me. Am I right to understand from you comments that you'd be in favour of it too? If so, do you want to resubmit the pull request (so that your name will be on the fix)?

Finally, should I be [temporarily] trying compilation with C99 to identify more potential issues?

**Comment by jief666** [comment]
I'm that proud of my name and this fix !! :-) Thanks for proposing.
I've committed it in the branch if it's easier for you. As you already have
done it in yours, you can close the pull request without merging (I guess
it's possible).

For C99, I didn't know they would be these warnings. Maybe it's some
function being renamed and improved, that's why the ones you use are
undefined in C99. I'm pretty sure these warnings would show up if there
really was some undefined. I was too quick saying these warnings should be
corrected. I apologize.

I did a lot of C a while back, but it wasn't about portability. It's was a
company proprietary server. So I'm not an expert in C portability.

**Comment by mikebrady** [comment]
Is there a chance that it might not?

**Comment by joerg-krause** [comment]
It's defined in C99, so some old compilers using C89 might not have it.

**Pull request merged**
