### PR TITLE
Replace PolarSSL with mbed TLS

### PR DESCRIPTION
**Pull request by thess**
First pass conversion from PolarSSL to mbed TLS -- It builds and starts. I need to find a client I can use for testing but this should get things started.

### CODE REVIEW

**Comment by thess** [comment]
Well, nice to see that Travis-CI is based on a nearly 3yr old distribution of Ubuntu! :-1:
No mbedTLS package. Nearest is jessie-backports.

**Comment by thess** [comment]
Not working yet - debugging... Need to redo `rsa_apply`.

**Comment by mikebrady** [comment]
Hi Ted. Many thanks for this. A couple of things.

First, is `PolarSSL` disappearing in general, or just from OpenWRT? If it's staying around, why not make `mbed TLS` an extra option and retain `PolarSSL`? It's important to have a fully compliant open source package for Debian, and OpenSSL is not compliant with their strict requirements. 

Second, I'm going to be away on business until about January 20, and won't have much time to look at this, so I won't have much feedback to offer.

**Comment by thess** [comment]
This version works now. Also fixed a stack smashing problem on 64-bit systems.

About PolarSSL. It is no longer supported and has been removed in a number of distros, including LEDE/OpenWrt. If you want to continue support for PolarSSL (it is still part of Trusty and Jessie I think), we can certainly do both it and mbedTLS.

**Comment by mikebrady** [comment]
Hi Ted. it seems that mbed TLS actually is a "rebranded" PolarSSL with slightly different licenses. Would that be your understanding of it – see https://en.wikipedia.org/wiki/Mbed_TLS? Also, it's not in Debian yet. So, I'd be thinking of continuing to support it but deprecating it for a while before dropping it. What do you think?

**Comment by thess** [comment]
Hi Mike -

From what I understand it is a major re-work with a lot more functionality. mbed TLS v1.3 (aka PolarSSL) is end-of-life and has already been removed from OpenWrt/LEDE. It is already gone in Ubuntu/Xerius too. I also seem to recall that building shairport with the latest mbed TLS on my Debian/Jessie system required the manual install of v2.x.

So, keeping both versions supported (where possible) makes sense for a bit. Going forward, you should default to the latest mbed TLS (currently 2.4). mbed TLS is now in jessie-backports, stretch & sid.

/ted

**Comment by mikebrady** [comment]
Hi Ted. Thanks again for all the work you've don on this. I have incorporated your changes in the `development` branch at commit 62aaf07478aa9883073133223878075bb411058b, but it is an addition or PolarSSL rather than a replacement. PolarSSL is now deprecated in Shairport Sync, and support will be withdrawn in the future.

**Comment by mikebrady** [comment]
Hi Ted. For Travis, did you get around that problem you mentioned above?

**Comment by thess** [comment]
No – apparently Travis dwells in the past. I’m not sure what it would take to include the mbed TLS, Jessie Backports, into the test environment. From what I’ve read on the topic, moving Travis to newer releases is not a priority.

It’s hard to imagine a tool for supporting development requires such a fixed point in time.

/ted

**Pull request closed without merging**
