### PR TITLE
s6 improvements and docker build changes

### PR DESCRIPTION
**Pull request by charlesomer**
Made changes to the way S6 runs the services within the container. Hopefully this is more stable. Now, when any of the services stop, S6 forces the container to also stop which makes problems more obvious.

Builds in a folder since it's now possible.

Uses `classic` rather than `airplay1` now.

Added template for GitHub issues as well as links to the Discussion topics when creating one. This can be previewed here: https://github.com/charlesomer/shairport-sync/issues/new/choose

### CODE REVIEW

**Comment by mikebrady** [comment]
Many thanks, Charles! Let me take a quick look over the weekend.

**Comment by mikebrady** [comment]
Thanks Charles!

**Comment by mikebrady** [comment]
Crikey, you've been busy, Charles!

**Comment by charlesomer** [comment]
I realised the issue template stuff won't appear until it's on `master` so I've created a separate PR for that here: https://github.com/mikebrady/shairport-sync/pull/1523

**Pull request merged**
