### PR TITLE
Arch Linux and Systemd support

### PR DESCRIPTION
**Pull request by omor1**
This adds a Systemd unit file alongside the existing SysV init script.
There is also an Arch Linux PKGBUILD and related installation files.
I have removed the init script installation from the Makefile – it prevents installation as non-root. Installation of init scripts should be up to the user and/or package manager.

The PKGBUILD will only be able to work well from version 2.1.16 onwards, as it relies on the new directory structure.

### CODE REVIEW

**Comment by mikebrady** [comment]
Many thanks for this! Due to work and other commitments, it'll be about two weeks before I can look at this properly. I hope that's okay.

**Comment by mikebrady** [comment]
Hi there. I'd like to test this out but don't have an Arch Linux installation. So I was going to install Arch Linux on a virtual machine. Would you have any pointers to how-tos or tutorials?

**Comment by omor1** [comment]
The [Arch Wiki](https://wiki.archlinux.org) is your friend – it's an amazing resource, even for people who do not use Arch. The [Beginners' guide](https://wiki.archlinux.org/index.php/Beginners%27_guide) and [Installation guide](https://wiki.archlinux.org/index.php/Installation_guide) are very good starting points. An easier option if you just want to get running is to use an [Arch-based distribution](https://wiki.archlinux.org/index.php/Arch_Based_Distributions_(Active)) such as [ArchBang](http://www.archbang.org) or [Antergos](http://antergos.com/).

**Comment by mikebrady** [comment]
Thanks – I'll try tomorrow.

**Comment by mikebrady** [comment]
Hi again. Thanks for the pointers. I'm using Antergos and it seems to play well with VMWare Fusion.

I'm trying to use the PKGBUILD script. A couple of issues:

1. Initially, I got this:
````
[mike@antergos tr]$ makepkg
==> Making package: shairport-sync 2.1.15-1 (Sat Jan 17 17:59:06 GMT 2015)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading ${pkgver}.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   135    0   135    0     0    204      0 --:--:-- --:--:-- --:--:--   204
curl: (22) The requested URL returned error: 404 Not Found
==> ERROR: Failure while downloading ${pkgver}.tar.gz
    Aborting...
````
This seemed to be caused by faulty quotation marks on line 10 of PKGBUILD. Removing the quotation marks made it go further. I also had to skip integrity checks.

This is as far as I've gotten: 

````
[mike@antergos tr]$ makepkg --skipinteg
==> Making package: shairport-sync 2.1.15-1 (Sat Jan 17 18:01:49 GMT 2015)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found 2.1.15.tar.gz
==> WARNING: Skipping all source file integrity checks.
==> Extracting sources...
  -> Extracting 2.1.15.tar.gz with bsdtar
==> Starting build()...
....
....
==> Entering fakeroot environment...
==> Starting package()...
Making install in man
make[1]: Entering directory '/home/mike/tr/src/shairport-sync-2.1.15/man'
make[2]: Entering directory '/home/mike/tr/src/shairport-sync-2.1.15/man'
make[2]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/home/mike/tr/pkg/shairport-sync//usr/share/man/man7'
 /usr/bin/install -c -m 644 shairport-sync.7 '/home/mike/tr/pkg/shairport-sync//usr/share/man/man7'
make[2]: Leaving directory '/home/mike/tr/src/shairport-sync-2.1.15/man'
make[1]: Leaving directory '/home/mike/tr/src/shairport-sync-2.1.15/man'
make[1]: Entering directory '/home/mike/tr/src/shairport-sync-2.1.15'
make[2]: Entering directory '/home/mike/tr/src/shairport-sync-2.1.15'
 /usr/bin/mkdir -p '/home/mike/tr/pkg/shairport-sync//usr/bin'
  /usr/bin/install -c shairport-sync '/home/mike/tr/pkg/shairport-sync//usr/bin'
make  install-exec-hook
make[3]: Entering directory '/home/mike/tr/src/shairport-sync-2.1.15'
[ -f /etc/init.d/shairport-sync ] || cp scripts/shairport-sync /etc/init.d/
cp: cannot create regular file ‘/etc/init.d/shairport-sync’: Permission denied
Makefile:918: recipe for target 'install-exec-hook' failed
make[3]: *** [install-exec-hook] Error 1
make[3]: Leaving directory '/home/mike/tr/src/shairport-sync-2.1.15'
Makefile:852: recipe for target 'install-exec-am' failed
make[2]: *** [install-exec-am] Error 2
make[2]: Leaving directory '/home/mike/tr/src/shairport-sync-2.1.15'
Makefile:798: recipe for target 'install-am' failed
make[1]: *** [install-am] Error 2
make[1]: Leaving directory '/home/mike/tr/src/shairport-sync-2.1.15'
Makefile:497: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
==> ERROR: A failure occurred in package().
    Aborting...
````
So, it looks like it's compiling and linking correctly, but I'm getting a permission denied error during installation. There might be an obvious solution, but I'm afraid I can't see it. The --asroot option is not allowed. Do I need to be member of wheel, or some such?

Thanks again for your work on this.

**Comment by omor1** [comment]
The problems you're having are almost certainly because the PKGBUILD is trying to download version 2.1.15, which uses the old directory structure and attempts to install the SysV init scripts directly into /etc.

If you replace the `source=('https://github.com/mikebrady/shairport-sync/archive/${pkgver}.tar.gz'')` line in the PKGBUILD with `source=('git+https://github.com/omor1/shairport-sync.git#branch=2.1-systemd')` (i.e. to point to my branch with these changes) it should work.

Once the changes are merged and 2.1.16 is released, the PKGBUILD should work.

**Comment by mikebrady** [comment]
I'll give it a try.

**Comment by mikebrady** [comment]
That looks better alright, thanks. Next issue on my installation is a stack-smashing abort. Doesn't happen if I configure using  `--with-ssl=openssl` Was that your experience? My system is: `Linux antergos 3.18.2-2-ARCH #1 SMP PREEMPT Fri Jan 9 07:37:51 CET 2015 x86_64 GNU/Linux`

**Comment by omor1** [comment]
I fixed a quote issue I noticed in the sources array.

Try downloading the newest version of the PKGBUILD, commenting out the sources line, and replacing it with `source=("${pkgname}-${pkgver}::git+https://github.com/omor1/shairport-sync.git#branch=2.1-systemd")`. This should force it to download the branch into 'shairport-sync-2.1.15', which makes it so you do not need to manually change each cd.

I'm on `Linux ArchVBox 3.18.2-2-ARCH #1 SMP PREEMPT Fri Jan 9 07:37:51 CET 2015 x86_64 GNU/Linux` – the exact same kernel as you are. The above changes work for me.

Make sure you have polarssl and git installed, and have the 'shairport-sync.install' file downloaded as well. If makepkg complains about integrity checks, run 'updpkgsums' and run makepkg again.

**Comment by mikebrady** [comment]
Okay, thanks. Made some more progress. Stack-smashing is gone as mysteriously as it arrived. Everything is peachy now, it seems, so I'm turning back to looking at System 5 issues.

I notice that you removed the `install-exec-hook` code from `Makefile.am`. It is useful in System 5 at `make install`, and so I'd prefer to leave it in place. Does it cause any problems in PKGBUILD? I realize that it doesn't work for Arch, but I could put a warning in README.md about that, for the time being at least.

**Comment by omor1** [comment]
I originally tried making a `--with-init=` flag for the `configure` script that would allow choosing between the SysV and Systemd init scripts, but I had issues getting that to work. At that point, I realized that the way it was currently set up made it impossible to install as non-root – I could set
`--prefix="$HOME/shairport-sync"`, but `make install` would nevertheless always try to install the SysV script to `/etc/init.d/`, which would fail as non-root. I believe it had issues with not obeying `DESTDIR` too.

I feel that init script installation and management is better performed by the package management system or manually by the user. init scripts are often different for each distribution and each one has different guidelines on how to run daemons – that's the reason there's a separate `shairport-sync.service` file for Arch and a generic one; the Arch install script will create a `shairport-sync` user to run the software under to increase safety, but not all distributions will do that. The init script is not strictly necessary to use the software, so it should not be installed automatically. Perhaps a separate make target (`make install-init`?) could be used, alongside the change to the `configure` script to choose between init systems.

**Comment by mikebrady** [comment]
Yeah, this is a dilemma alright. It seems to me that a very clean solution is to do something like what's done for Shairport Sync for OpenWrt – have a separate repository for the Arch Linux scripts, with the three files – PKGBUILD, shairport-sync.install and shairport-sync.service – and a README.md file. This would solve all the problems, it seems to me; you'd have a clean Arch Linux solution and the main repository would remain clean. Do you want to try it or shall I? Since you've done all the work, I think it should be you!

**Comment by EliaCereda** [comment]
Hi, sorry to jump in so late. I've been following this discussion for a while, but I hadn't found the time to reply yet. 

I've been using shairport-sync with Arch for a few months now and I have a PKGBUILD around that I planned to share but I never actually did it.

It's actually pretty clean as it doesn't need to make any changes to the source code, except for a patch applied automatically at build time that disables the SysV init script. It also uses libsoxr for resampling, it allows to pass options to the daemon and control it with `shairport-sync -P`. The only problem is that it runs the daemon as root at the moment, but that can be easily fixed. It also needs testing with the latest versions of shariport-sync because I'm still using v2.1.11 on my Raspberry.

I've uploaded a copy of the files here, feel free to give it a try and make any improvements: https://gist.github.com/EliaCereda/0746809ab18e37dec7a8

**Comment by mikebrady** [comment]
Thanks @EliaCereda for that. I subsequently found another on the Arch User Repository (AUR) at https://aur.archlinux.org/packages/shairport-sync/.

**Comment by omor1** [comment]
@EliaCereda I decided against using `libsoxr` due to the warnings stating that may require greater processing power. Have you had any issues using `libsoxr` on your Raspberry Pi? If not I may add it to my `PKGBUILD`. I used `PolarSSL` instead of `OpenSSL` since I believe it has lower memory usage, and I already had software installed that used `PolarSSL` (`µmurmur`, to be exact). I'm not sure how much the choice of SSL library matters. Thoughts?

@mikebrady I originally found the `AUR` pkg, but I disliked the way it was written, especially with regards to the Systemd script – It's much safer to run software with the minimum permissions needed, which my method does by creating the `shairport-sync` user. I also did not like the fact that it needed to patch out the installation of the SysV init script, since I don't think the installation should be there in the first place. However, if you think differently, I'll acquiesce to your opinion.

**Comment by mikebrady** [comment]
Hi @omor1. A couple of things.
* If you include `libsoxr` in the compilation, it doesn't force you to use the `soxr` stuffing mode at runtime – it just makes it an available option. However, it does mean that the `libsoxr` library has to be in the system, even if it isn't used. This may be undesirable because of space constraints.
* I added support for using PolarSSL because it is somewhat more in keeping with the strict requirements of Open Source. I'm not sure about its performance relative to OpenSSL.
* I think the SysV init script will have to stay, as it's widely used, and – importantly – it's what users now expect from this repository.
* I like the idea of defining a less-privileged user for shairport-sync itself, and it seems to me that it's a good feature of your script.

On balance, I think the best thing is for you to make the script a separate repository, and so, I respectfully decline the pull request. I would be happy to point to your repository in the README document. 

I'd like to thank you for your help and guidance in starting my journey in Arch Linux.

**Comment by EliaCereda** [comment]
@omor1 In my experience `libsoxr` works flawlessly on Raspberry Pi: CPU usage is higher than with basic interpolation but it abundantly stays within comfort levels (IIRC usage goes from 8-10% with basic to 20-25% with libsoxr). Your mileage could vary, but I think the Raspberry is perfectly able to handle `libsoxr`.
Regarding PolarSSL, I didn't put a lot of thought into the matter because I'm not doing anything else with my Raspberry at the moment, so I didn't feel the need to optimize memory usage and OpenSSL's memory usage isn't that high anyway. Feature-wise and performance-wise they should be almost on par, with OpenSSL possibly faster due to better processor-specific optimizations (I haven't tested them first-hand though, it's just what it's being reported on the Internet).
I guess the best choice would be to stick with OpenSSL (which is pretty much guaranteed to be already installed on every Raspberry - or every Linux machine for that matter). Those who desire to use PolarSSL can always edit the PKGBUILD and build the package with the flags they choose. That's the standard way to deal with custom build options on Arch anyway.

@mikebrady As `libsoxr` binary package only takes up 185KB of disk space when installed, I think shairport-sync should enable it by default at build time. Or, if you could check at runtime whether the library is installed or not, `libsoxr` could even be marked as an optional runtime dependence and the problem would be solved altogether.

**Comment by mikebrady** [comment]
Thanks @EliaCereda! But, but – I'm about to release shairport-sync 2.2 – it's in the repository but is not yet the default branch. Everything compiles the same as 2.1.15 but the checksums and rev number will be different.

**Comment by EliaCereda** [comment]
You're welcome!

No problem, I've updated the PKGBUILD to pick up the source code from the HEAD of this repo: this way, as soon as you release the update, the package will automatically use it. The checksums are not used for git repositories and the version of the package is generated at build time by the [`pkgver()`][1] function in PKGBUILD (the version at [line 4][2] is just indicative, `makepkg` will update it when it builds the package), so everything will be ready when you decide to release.

[1]: https://github.com/EliaCereda/shairport-sync-PKGBUILD/blob/master/PKGBUILD#L25
[2]: https://github.com/EliaCereda/shairport-sync-PKGBUILD/blob/master/PKGBUILD#L4

**Comment by davclark** [comment]
I'm trying to figure out what happened here. It seems like everyone was on board about including systemd scripts from @omor1's fork, but then this pull request was closed. Did those scripts get merged somewhere? Or should I just use the fork for now?

**Comment by mikebrady** [comment]
I suggested that he should put his scripts in a separate repository – see the post from January 25 – and I would put a link to it in the README.

**Pull request closed without merging**
