### PR TITLE
ci: build docker with pa

### PR DESCRIPTION
**Pull request by nipsufn**
Can I have images with PulseAudio support on DockerHub please?
I shuffled things around a bit to avoid some code repetition and added image building without pushing on branches starting with `ci/`. I could add some more arguments and have just one Dockerfile if that's welcome, probably merge `tag` and `push` workflows into one file, but I didn't want to propose too big of a revolution from a get-go.
It will create conflicts with #1624. I can rebase and clean up this after #1624 is merged if needed.

### CODE REVIEW

**Comment by mikebrady** [comment]
Many thanks for your work on this. Not being a Docker expert, it's very interesting to see how you have gone about the image building. It'll take me some time to get through it.

A couple of things.

1. #1624 is looking quite promising -- though there are a few things to clarify first.
2. Your PR is to the `master` branch, but it should really be to the `development` branch. That way, if it's accepted, it would be in the `development` branch for testing and evaluation before going into the `master` branch.
3. More specifically, regarding support for PulseAudio, how would the image access the PulseAudio infrastructure provided by the host? Could you give an example of, say, how the Docker image would be invoked and the command-line options you would have to add to it to allow access to the PulseAudio system, please?
4. To the best of my knowledge, the PulseAudio service is only available after a user has logged in through the GUI. Does it not follow that a Docker image that is automatically started would not have access to the PulseAudio service? If so, does that mean that the Docker image would have to be invoked as a user service?

**Comment by noelhibbard** [comment]
Another option is you disable the user mode pulse service and add create a system wide pulse server. I have a ready made service file here: https://github.com/noelhibbard/sharport-sync-docker/blob/master/pulseaudio.service

So the process would be something like this:
```bash
sudo systemctl --global disable pulseaudio.service pulseaudio.socket
sudo adduser pulse audio
sudo systemctl --system enable /path/to/the/service/file/linked/above/pulseaudio.service
sudo systemctl start pulseaudio.service
```

The system wide service uses this config file ```/etc/pulse/system.pa```.

Also, the PULSE_COOKIE env var isn't needed if ```auth-anonymous=1``` is set.

**Comment by mikebrady** [comment]
Thanks for your inputs, @nipsufn and @noelhibbard. So, what's the verdict? Would it be worth incorporating a little more PulseAudio support -- specifically, the  `libpulse` library -- in the standard image, so that interested users could use the standard image in PulseAudio applications in the ways envisaged above? Would that be a good idea?
Thanks again.

**Comment by nipsufn** [comment]
I'm OK with just enabling PA backend on existing images, that should result in pretty minimal changes compared to what I'm proposing here and it gets me what I'd find useful. It does seem though to contradict pattern established with having separate AP1/AP2 images rather than flag/config to control which one of those is used.

**Comment by mikebrady** [comment]
Thanks @nipsufn. Combining the PulseAudio and ALSA versions in one Docker image should make ongoing maintenance a bit simpler. Having to maintain separate AP1 and AP2 images is also something I'd like to move away from, but the differences between them are quite considerable at the moment.

**Comment by mikebrady** [comment]
I haven't forgotten this -- just there's a lot going on! Thanks for your patience.

**Comment by mikebrady** [comment]
Hi @nipsufn, @noelhibbard, @curiousercreative. Just trying out these ideas on the latest version of Shairport Sync. 

@nipsufn, could you state what's in the file `./pulseaudio.client.conf` that you refer to above, please?

(I'm not a PulseAudio guy, I'm afraid.)

**Comment by noelhibbard** [comment]
> Thanks for your inputs, @nipsufn and @noelhibbard. So, what's the verdict? Would it be worth incorporating a little more PulseAudio support -- specifically, the `libpulse` library -- in the standard image, so that interested users could use the standard image in PulseAudio applications in the ways envisaged above? Would that be a good idea? Thanks again.

My client.conf is completely empty. I run PA as a system wide service on my host machine and the critical line that is needed in the system.pa file is this:
```
load-module module-native-protocol-unix auth-anonymous=1 socket=/var/run/pulse/native
```

Then my docker compose looks _something_ like this:
```
services:
  SPS-Bathroom:
    container_name: SPS-Bathroom
    image: shairport-sync:pulse # this points to my custom sps build which I tagged 'pulse'
    restart: unless-stopped
    volumes:
      - ./shairport-sync-bathroom.conf:/etc/shairport-sync.conf
      - /var/run/pulse:/var/run/pulse # this maps the pulse socket from the host into the container
      - ./logs:/var/logs/shairport-sync
    environment:
      - PULSE_SERVER=unix:/var/run/pulse/native # this tells pulse within the container where to reach the PA server that runs on the host
```

**Pull request merged**
