### PR TITLE
use s6 process manager in Docker container.

### PR DESCRIPTION
**Pull request by robcast**
Here is a refactoring of the current "start.sh" script that starts all processes (avahi, dbus, nqptp, shairport-sync) using the https://github.com/just-containers/s6-overlay system.

The s6 system should be better at dealing with signals, zombie processes, running processes under different user-ids, and it is a cleaner setup with separate configuration for each service.

I am no wizard in process handling, so there may be errors, but this setup works for me ;-)

### CODE REVIEW

**Comment by charlesomer** [comment]
Thank you, I’ll try to have a look at this tonight 👍

**Comment by charlesomer** [comment]
This seems like a sensible thing to be doing and s6-overlay looks like the best option at the moment. I'm making some other changes so I'll add this in as part of that I think. I'll leave this open for now though - thank you!

**Comment by charlesomer** [comment]
New PR opened #1378 which includes s6-overlay and other improvements.

**Comment by mikebrady** [comment]
Hi Robert. Thanks for the Pull Request. As you'll see, Charles has incorporated your ideas into a larger reworking of the workflow.

Thanks again.

**Comment by robcast** [comment]
I'm happy this was helpful :-)

And thanks again for all your work on the beautiful shairport-sync!

**Pull request closed without merging**
