### PR TITLE
Migrate to new HA mqtt configuration

### PR DESCRIPTION
**Pull request by hunhejj**
The old way of configuring mqtt entities is not supported anymore since `v2022.12`

### CODE REVIEW

**Comment by mikebrady** [comment]
Thanks for your pull request.

> The old way of configuring mqtt entities is not supported anymore since v2022.12

Not being an MQTT expert, would you be kind enough to point me at a summary of the changes, please?

**Comment by hunhejj** [comment]
The new way of configuring MQTT sensors in HomeAssistant is described here: https://www.home-assistant.io/integrations/sensor.mqtt. The announcement about the migration is described here under MQTT: https://www.home-assistant.io/blog/2022/06/01/release-20226/#breaking-changes.

**Comment by mikebrady** [comment]
Thanks for that, and thanks for the follow-on PR too.

Okay, so the remaining issue is that the PRs are to the `master` branch, but it would be [much more preferable](https://github.com/mikebrady/shairport-sync/blob/master/REPORTING%20ISSUES.md#pull-requests) to target the `development` branch, if possible.

**Comment by hunhejj** [comment]
Ok, rebased @mikebrady.

**Pull request merged**
