### PR TITLE
add meson build system support

### PR DESCRIPTION
**Pull request by lrusak**
Hello!

I was working on another project (https://github.com/lrusak/shairport-display) and figured I could help out shairport-sync by updating it's build system.

meson is really simple and fast (in combination with ninja).

I wrote this to follow closely to what the autotools build already provides, however, I cannot test every option as I only use linux. I do consider it a good start though and a large improvement over the autotools build. The usage strings can probably be improved but I just copied them from the autotools build.

usage is as such:
```
mkdir -p build && cd build
meson -Dssl=openssl -Dalsa=true -Ddbus=true -Dpa=true -Davahi=true -Dmetadata=true -Dinstall_config_files=true -Dsystemd=true --prefix=/usr ..
ninaj
sudo ninja install
```

If this isn't something that you want then no hard feelings, I just wanted to contribute back to a project that I am consuming for use with my own project.

### CODE REVIEW

**Comment by mikebrady** [comment]
Thanks for the suggestion. I'll have a look!

**Comment by mikebrady** [comment]
Thanks again for your suggestion. I took a look at it, and at present I don't think it offers enough of an advantage to take on board, so I will respectfully decline the pull request. I'll certainly look at it for future projects.

**Comment by lrusak** [comment]
No worries, I hope you do reconsider at some point as autotools is absolute garbage compared to modern build systems :smile_cat:

**Comment by lrusak** [comment]
just checking in a year later, are you still set on autotools? 😄

**Comment by mikebrady** [comment]
Haha, thanks for the reminder, Lukas! Still stuck on `autotools` alright. Found a few mhistakes in it in the intervening year, but busy doing something deep inside Shairport Sync right now... 😊

**Comment by lrusak** [comment]
No worries 😺 I'm still using this project daily 👍 

Here is a very rudimentary metric showing the difference on my RPi3b
```
$ time ../configure
<snip>
../configure  25.59s user 13.89s system 99% cpu 39.692 total
```

```
$ time meson ..
<snip>
meson ..  6.62s user 2.52s system 102% cpu 8.895 total
```

**Pull request closed without merging**
