### PR TITLE
use sysconfdir not $(DESTDIR)/etc for config files

### PR DESCRIPTION
**Pull request by ilovezfs**

### CODE REVIEW

**Comment by mikebrady** [comment]
Thanks for this. What is the purpose of the change you propose?

**Comment by ilovezfs** [comment]
@mikebrady hi there. I'm one of the Homebrew maintainers and noticed that the sharport-sync formula was due for an update. We like to re-assess formulae when they come due for update, and I noticed whoever originally put it together was not installing your config files and was putting the pid file in the prefix. Since we set prefix not DESTDIR, the default will try to use /etc if you enable config files, which will cause a sandbox violation. In particular, we like to set sysconfdir to /usr/local/etc/foo not /usr/local/Cellar/foo/2.8.4/etc since the former is preserved across upgrades, which is usually preferable to simply outright replacing config files the user may have modified. Hence, https://github.com/Homebrew/homebrew-core/pull/3827.

Please let me know if you'd like any other changes to that PR (or this one!)

**Comment by ilovezfs** [comment]
@mikebrady also, the reason I added the `--with-metadata` option is https://github.com/mikebrady/shairport-sync/issues/356.

**Comment by ilovezfs** [comment]
>Pretty sure I fixed that #356 bug too...

@mikebrady odd, since that's a HEAD build

**Comment by mikebrady** [comment]
Are you looking on the master it development branch? The development branch is where it's all happening :)

**Comment by ilovezfs** [comment]
@mikebrady our head spec is pointing at master, but that is clearly wrong. Setting it to the development branch, the bug went away! :)

**Comment by mikebrady** [comment]
Yeah, fixes and improvements are put into the development branch for a while before they make it into the master. That particular bug was a silly thing I did.

**Comment by mikebrady** [comment]
Hi there. Thanks again for this suggestion, but it looks somewhat rocky.

Firstly, if I'm not mistaken, your suggested change would break some installation packagers – see https://www.gnu.org/prep/standards/html_node/DESTDIR.html#DESTDIR and https://www.gnu.org/prep/standards/html_node/Directory-Variables.html (and see also #115).

Secondly, the default value for `$sysconfdir` is `${prefix}/etc`, and `$prefix` evaluates to `/usr/local`, but `/usr/local/etc` is not widely used in Linux.

**Comment by ilovezfs** [comment]
Deliberately ignoring `--sysconfdir` incoming from configure is a bug no matter how you slice it ...

**Comment by ilovezfs** [comment]
@mikebrady https://www.gnu.org/software/automake/manual/html_node/Hard_002dCoded-Install-Paths.html

**Comment by p3ck** [comment]
I think the correct syntax would be as follows:
+	[ -e $(DESTDIR)$(sysconfdir) ] || mkdir $(DESTDIR)$(sysconfdir)

Under normal conditions $DESTDIR will be empty. but for packagers it will be defined and should work.

I will test this later by building an rpm with this change.

**Comment by ilovezfs** [comment]
@p3ck fixed, thank you.

**Comment by mikebrady** [comment]
Thanks @p3ck – something that fixes the `$DESTDIR` problem with the original PR, but the `sysconfdir` issue remains.

To begin recognising the value of `sysconfdir`, the instructions for `./configure` in any Linux would have to change to include a `--sysconfdir=/etc` directive. Is there any nice way around that?

BTW, could you make the PRs work on the `development` branch please.

**Comment by ilovezfs** [comment]
To quote from the link above

>by default sysconfdir will be ‘$(prefix)/etc’, because this is what the GNU Standards require. When such a package is installed on an FHS compliant system, the installer will have to set ‘--sysconfdir=/etc’. As the maintainer of the package you should not be concerned by such site policies: use the appropriate standard directory variable to install your files so that the installer can easily redefine these variables to match their site conventions. 

Basically, that's a totally normal expectation for packaging on Linux.

**Comment by mikebrady** [comment]
Yeah, I'm afraid you might be right...

**Comment by mikebrady** [comment]
Hi there. Would you be kind enough to retarget this to the `development` branch please. Then I'll include it. It'll be necessary to update the documentation too, but I'll get to that.

**Comment by ilovezfs** [comment]
@mikebrady https://github.com/mikebrady/shairport-sync/pull/357.

**Pull request closed without merging**
