### PR TITLE
README: add a note about Debian

### PR DESCRIPTION
**Pull request by bootc**
Add a note to `README.md` that a version for Debian is now available.

### CODE REVIEW

**Comment by mikebrady** [comment]
Many thanks Chris.

**Comment by mikebrady** [comment]
I took about the reference to the tracker – it wouldn't work for me, I'm afraid.

**Comment by bootc** [comment]
What kind of issues did you run into? Seemed to work for me; it's just a link over to Debian.

**Comment by mikebrady** [comment]
It is rejecting my attempt to link from Safari. Just tried it in Chrome and it worked. I'll put it back...

**Comment by bootc** [comment]
Curious. I'll give it a try myself once it's back and see what's going on.

**Comment by mikebrady** [comment]
It seems to be a problem with certificates in Safari. I think it might be specific to my machine – it seems to be a "known problem" with Safari that this happens occasionally.

**Comment by mikebrady** [comment]
BTW, if you come across other typos or infelicities, please don't hesitate to let me know.

**Comment by bootc** [comment]
Hmm, it could be because the site requests an optional client certificate - I just tried that in Safari and it got a little confused asking me about them.

I do have some more typos and things to send you! :-) I'll do a more thorough review of the development branch over the weekend I hope and send you a few over, but I wanted to get 2.8.0 uploaded to Debian ASAP first, so I fixed those the automated tools complained about first.

**Comment by mikebrady** [comment]
Great – you'll find I had already put in something about the Debian developments, but you text is better!

**Comment by mikebrady** [comment]
Also, it's very likely that 2.8.1 will be out soon, certainly before the end of next week – it has a workaround for a TuneBlade problem and will have some stability improvements. I'll merge them into the `development` branch today. Time willing, I could incorporate your stuff before release.

**Pull request merged**
