### PR TITLE
Added option for mono output

### PR DESCRIPTION
**Pull request by faceless2**
HI Mike - trying again with a new pull request against the development branch to add the "mono" option.

### CODE REVIEW

**Comment by mikebrady** [comment]
Hi. I was thinking of changing the option to something like `playback_mode = "mono"` with the options being `stereo` and `mono` to begin with. Is that okay with you? The motivation is that it will allow more options to be added later.

**Comment by faceless2** [comment]
Sure, doesn't bother me either way. Good idea.

**Comment by elliottwilliams** [comment]
Sorry about bringing up a closed issue, but I was noticing some poor audio quality when switching my config over to mono. Some audio was clipping, and it hadn't been in stereo.

Looking at the code in this PR, I think the problem is that the mono algorithm adds left and right samples together, without adjusting for two samples' worth of amplitude in a single sample. This means that a stereo sample that isn't clipped could clip when converted to mono. We could avoid this by adding the two left and right samples together and dividing the sum by 2.

If you'd like, I can try this out, see if it sounds correct, and submit a PR.

**Comment by mikebrady** [comment]
Thanks. Let me check it out – I thought it dealt with clipping.

**Comment by faceless2** [comment]
Yep, you're absolutely right. There are two ways to convert stereo to mono - add the samples together, or add them and divide by two. The first option will occasionally result in clipping of the waveform, the second option will halve the volume of the output. I tested both and felt the first was the lesser of the two evils.

No doubt there are other approaches, but none I can think of that are practical in realtime without prior analysis of the audio stream.

**Comment by mikebrady** [comment]
Just thinking about this. Would it be true to say that the procedure of just adding the two samples together violates the [Principle of Least Surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment)?

Consider if the two channels were already mono, then the two outputs would also be mono but doubled in volume.

On the other hand, if the procedure was to add the two samples and divide by two, two mono signals in would result in two identical mono signals out.

If that's the case, then using the second procedure is less "surprising" and therefore, IMHO, more appropriate. Futheremosr, could not the effect of the first procedure could be obtained by just turning the volume up by 6 dB?

**Comment by faceless2** [comment]
All I know is when I tried it on a regular stereo sample, it was noticeably quieter. Surprisingly so, if you like. Whichever way it goes you're going to lose fidelity, the question is would you rather lose 6dB (bad on an underpowered amp) or risk clipping (bad on an over-compressed track). Starting with a mono track is not the typical case so I'm not sure it's worth focusing on that.

I think you can easily make this argument both ways - so long as there's a choice between add or add-and-halve, then personally I don't mind which is the default. Either way I would certainly suggest trying it out before you make the decision on which is the default, it's easy enough to test.

**Pull request merged**
