### PR TITLE
Jack output add soxr resampling

### PR DESCRIPTION
**Pull request by pdgendt**
First attempt at adding soxr resampling to the jack audio output, I thought I would share it already.
Some notes:
- [ ] Configurable buffer size would be an improvement
- [ ] Tested with soxr "very high" resampling quality, other options are barely tested!
- [ ] TODO: Describe config options in `scripts/shairport-sync.conf`

### CODE REVIEW

**Comment by mikebrady** [comment]
Thanks for this contribution. I wonder if Jörn Nettingsmeier (@nettings) would have a view...

**Comment by mikebrady** [comment]
Hi there. No response from Jörn. 

One little thing. Could you change `jack.soxr_resample_recipe` to `jack.soxr_resample_quality` please? It makes more sense to me...

**Comment by mikebrady** [comment]
Thanks!

**Comment by nettings** [comment]
Hi, sorry for the late reply, the end of the year was insanely busy! I'm really excited about this feature and pulling it into my test environment as I'm typing this. Will report back.

**Comment by nettings** [comment]
Yay! Running my jackd server at 48k now, with shairport-sync resampling merrily. Hartelijk dank @pdgent ! Now I'm trying to understand how you're doing it.

**Pull request merged**
