### PR TITLE
clarify readme with respect to multi-room iOS support

### PR DESCRIPTION
**Pull request by dasl-**
This confused me when I was getting started with shairport-sync recently. Fingers crossed that airplay 2 compatibility eventually makes it so that this becomes a non-issue :)

### CODE REVIEW

**Comment by mikebrady** [comment]
I'd like to pause merges for a few weeks, if you don't mind.

**Comment by JesseRiemens** [comment]
Seems like a good addition, I was confused as well.

**Comment by mikebrady** [comment]
Thanks, yeah, I haven't forgotten. 😊

**Comment by mikebrady** [comment]
Hi there. As you may have gathered, the `development` branch of Shairport Sync now offers AP2 and multi-room operation from iOS devices, so your observation might be moot. Therefore, I will respectfully decline you request. May thanks for your interest in improving Shairport Sync!

**Pull request closed without merging**
